### ISSUE TITLE
[Question]可以在go-admin里面写对外的接口和页面吗？

### ISSUE THREAD

**Issue by dotcool** [GoAdminGroup/go-admin#103]
**问题描述** [详细地描述问题，让大家都能理解]
比如gin可以直接写页面，不用走admin授权么
**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
@dotcool 目前有ap可以，但是是需要授权的。文档：http://www.go-admin.cn/docs/#/pages/pages 如果要不授权的话，需要自己根据授权的这个定制写一个。
