### ISSUE TITLE
[Question] 图片字段，用的类型是文件，当我编辑这条记录以后图片就没了

### ISSUE THREAD

**Issue by dotcool** [GoAdminGroup/go-admin#105]
**问题描述** [详细地描述问题，让大家都能理解]

比如新建的时候上传图片和保存数据是好的，但是我这边编辑这个数据，比如标题，图片显示的是udid的一串字符串.png。但是我点击保存列表里面的文件数据就没了。

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
@dotcool  能不能试一下，看看能不能在demo中重现：https://demo.go-admin.cn/

**Comment by dotcool** [comment]
demo里面没有图片呢。我是编辑图片的时候出现这个问题哦

**Comment by dotcool** [comment]
admin的个人资料编辑，如果传图片，也是会挂的哦

**Comment by chenhg5** [comment]
@dotcool 什么浏览器

**Comment by dotcool** [comment]
chrome

**Comment by godcong** [comment]
更新的时候因为你没上传文件,所以空的字符就把你那个uuid覆盖掉了.
我也遇到过这个问题. 我本地代码改了go-admin的加了个HOOK
@chenhg5 能不能加个BeforeInsert和BeforeUpdate的Hook,有些字段可能需要自己手动修正下的.

**Comment by chenhg5** [comment]
@dotcool @godcong 这个问题新版本中应该是解决了。另，before Insert/Update的[Hook](http://doc.go-admin.cn/zh/admin/form/basic/#_18)也有提供。
