### ISSUE TITLE
[Proposal] 能否提供iframe版？

### ISSUE THREAD

**Issue by wenbingzhang** [GoAdminGroup/go-admin#106]
如题，我个人感觉单页版自由度不是很高。

**Comment by chenhg5** [comment]
@wenbingzhang 自由度是指什么？能不能举具体功能例子。

**Comment by keeleys** [comment]
> @wenbingzhang 自由度是指什么？能不能举具体功能例子。

一般后台管理除了curd，还有给前端的restful api ，前端可能也会公用一些增删改查。
那这个项目怎么集成restful呢，还是说在开个新项目 类似`chenhg5/ko`的专门做api。

**Comment by wenbingzhang** [comment]
@keeleys  api还是好解决，用插件就能解决。需要高度定制的时候就感觉自由度不够了。另外需要外嵌入一些页面的时候也不行。

**Comment by chenhg5** [comment]
@wenbingzhang 嵌入页面是指？现在是可以自己写一个页面，可以在返回内容中嵌入iframe，如果是在表格中的话，当前最新版本支持点击按钮有popup，popup的内容可以自定义（也可以嵌入iframe），下个版本会支持更多布局，比如表格上方下方增加自定义内容，会提供一下api，iframe这个也可以考虑。

**Comment by wenbingzhang** [comment]
> @wenbingzhang嵌入页面是指？现在是可以自己写一个页面，可以在返回内容中嵌入iframe，如果是在表格中的话，当前最新版本支持单击按钮有popup，popup的内容可以自定义（也可以嵌入iframe ），下个版本会支持更多布局，并在上方增加自定义内容的表格，会提供一下api，iframe这个也可以考虑。

点击某个菜单，支持iframe打开页面就行。

**Comment by chenhg5** [comment]
@wenbingzhang 可以看下这里：https://book.go-admin.cn/zh/admin-cha-jian/shu-ju-biao-ge/basic#xin-zeng-an-niu

**Comment by wenbingzhang** [comment]
@chenhg5 这个是添加一个Button点击并弹窗吧？

**Comment by wenbingzhang** [comment]
@chenhg5 其实就是需要实现 iframe版admin。

**Comment by wenbingzhang** [comment]
@chenhg5 希望在菜单中打开一个外部的网友，不是新建一个tab或新的窗口，而是iframe方式打开。

**Comment by chenhg5** [comment]
@wenbingzhang 应该不难实现 我看一下

**Comment by chenhg5** [comment]
@wenbingzhang 增加一个例子：https://github.com/GoAdminGroup/example/blob/master/main.go#L88

**Comment by wenbingzhang** [comment]
@chenhg5  谢谢，这个变通的方式确实可行，就是有点不方便。每加一个还需要添加一个路由，还是希望能直接在菜单中添加的方式支持。

**Comment by chenhg5** [comment]
@wenbingzhang iframe的popup已经在新版本中提供。
