### ISSUE TITLE
choose table to generate  [Use arrows to move, enter to select, type to filter]

### ISSUE THREAD

**Issue by keeleys** [GoAdminGroup/go-admin#107]
**问题描述** [详细地描述问题，让大家都能理解]
当我点击enter的时候 直接提示 `go-admin cli error: no table is selected。`
我不知道怎么样才能勾选我创建的table。

GoAdmin CLI v1.1.1
mac 10.14.6 
iterm2 + zsh

**示例代码** [如果有必要，展示代码，线上示例，或仓库]
```
? choose a driver mysql
? sql address 127.0.0.1
? sql port 3306
? sql username root
? sql password ********
? sql database name godmin
? choose table to generate  [Use arrows to move, enter to select, type to filter]
> [ ]  users
  [ ]  users2
```
**其他信息** [如截图等其他信息可以贴在这里]
```
go-admin cli error: no table is selected
```

**Comment by chenhg5** [comment]
@keeleys 用空格选择，但是你这个的提示错了，你是自己编译的cli吗，还是下载的？

**Comment by keeleys** [comment]
> @keeleys 用空格选择，但是你这个的提示错了，你是自己编译的cli吗，还是下载的？

谢谢 空格可以。是直接 `go install github.com/GoAdminGroup/go-admin/adm` 安装的
