### ISSUE TITLE
[Question] Using non sql based resources

### ISSUE THREAD

**Issue by samvdb** [GoAdminGroup/go-admin#108]
Looking at the code, I see no obvious way to integrate resources from grpc services or api's.
Only SQL type drivers are supported and this is locked into the Tables interface with these methods:

```go
GetDataFromDatabase(path string, params parameter.Parameters) (PanelInfo, error)
GetDataFromDatabaseWithIds(path string, params parameter.Parameters, ids []string) (PanelInfo, error)
GetDataFromDatabaseWithId(id string) ([]types.FormField, [][]types.FormField, []string, string, string, error)
UpdateDataFromDatabase(dataList form.Values) error
InsertDataFromDatabase(dataList form.Values) error
DeleteDataFromDatabase(id string) error
```
A complete override of these methods would be one way to go, or figure out how to make this more generic.

Any suggestions for this?

**Comment by chenhg5** [comment]
@samvdb Yes, I have considered that. The separation of different data source I will focus on. A possible solution now might be specifying a unified data source format which comes from JSON API or SQL database or any other way. And GoAdmin receives the data and make it display in the panel.

**Comment by samvdb** [comment]
Currently i am constructing a custom page ( so not going through the admin table list ).
As an example:

```go
func ShowOperation(ctx *context.Context) {
	//param := guard.GetShowFormParam(ctx)

	page.SetPageContent(ctx, auth.Auth(ctx), func(ctx interface{}) (types.Panel, error) {

		c := ctx.(*context.Context)
		panel := table.NewDefaultTable(table.DefaultConfig)
		params := parameter.GetParam(c.Request.URL.Query(), 100, panel.GetPrimaryKey().Name,
			panel.GetInfo().GetSort())

		infoPanel := panel.GetInfo()
		infoPanel.AddField("ID", "operation", db.Integer)
		templ := template.Get(config.Theme)

// Create an InfoList map with data from your service


		dataTable := templ.DataTable().
			SetInfoList(panelInfo.InfoList).  // Set the InfoList 
			SetPrimaryKey(panel.GetPrimaryKey().Name).
			SetThead(panelInfo.Thead)

		box := templ.Box().
			SetBody(dataTable.GetContent()).
			SetHeader(dataTable.GetDataTableHeader() + panel.GetInfo().HeaderHtml).
			WithHeadBorder(false).
			SetFooter(panel.GetInfo().FooterHtml + panelInfo.Paginator.GetContent()).
			GetContent()

		return types.Panel{
			Content:     box,
			Title:       "example",
			Description: "",
		}, nil
	})
}
```
I hope this sample code helps other people create a custom table.
Forms can be customized by using the Insert and Update hooks so that's not an issue.


Great project btw! It's quite simple to create custom pages or show CRUD's for resources.
