### ISSUE TITLE
[Proposal] go-admin 样式Date需求 + 静态资源文件开放

### ISSUE THREAD

**Issue by ZhangIvan** [GoAdminGroup/go-admin#110]
**需求描述** [详细地描述需求，让大家都能理解]

1. 希望在form中设置过滤时自动根据字段类型实现过滤样式，比如数字 类型 =>> 前端可实现数字大于等于小于等界面效果操作；时间类型时 =>> 自动渲染时间格式的界面，如:
![image](https://user-images.githubusercontent.com/25630763/70400897-1b96a580-1a68-11ea-8960-0c4b6e584715.png)

2. 希望可以在form中增加Date类型，目前看到了Datetime，虽然差不多，但是齐全的话，强迫症还好点，嘻嘻；

3. 尝试自己修改源码来支持界面需求，但发现静态资源文件都是打包成了go文件，可以考虑暴露开放么？如果开放的话，打包方式什么的注意事项有不？

感谢作者的支持，谢谢

**解决方案** [如果你有解决方案，在这里清晰地阐述]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by ZhangIvan** [comment]
补充下，

4.  form中文本过滤我建议应该是模糊匹配，当然也可以精确匹配多种选择，当已经使用过条件过滤后，再次点击过滤，我认为应该会显上次的过滤条件，在url上可以获取到；
![image](https://user-images.githubusercontent.com/25630763/70405527-70421c80-1a78-11ea-939a-476e8fc7f441.png)

![image](https://user-images.githubusercontent.com/25630763/70405531-759f6700-1a78-11ea-8893-fe4d6dba21eb.png)

5. 如何定义 按钮Action？ 好像未在文档中发现该描述。。。。。。
比如：我想新建一个自定义的按钮事件，或者是在按钮 “操作” 下继续新建事件，该如何处理？

![image](https://user-images.githubusercontent.com/25630763/70405663-f0688200-1a78-11ea-82e8-41d5a8850244.png)

**Comment by chenhg5** [comment]
@ZhangIvan 关于筛选，今晚更新版本，支持更多操作。目前可参考demo：https://demo.go-admin.cn/admin

**Comment by chenhg5** [comment]
@ZhangIvan 新增按钮，我一会更一下文档，文档还没更新。最新版本是可以自定义按钮与操作

**Comment by chenhg5** [comment]
@ZhangIvan 已更新[文档](http://www.go-admin.cn/docs/#/admin/table/basic?id=%e6%96%b0%e5%a2%9e%e6%8c%89%e9%92%ae)。
