### ISSUE TITLE
[Proposal]希望Info增加显示详情页面info/show等

### ISSUE THREAD

**Issue by bitepeng** [GoAdminGroup/go-admin#112]
**需求描述** 
1. 希望Info增加显示详情页面info/show，用于显示单条数据的详情
2. 希望数据表格里的日期格式可以设置或默认为 Y-m-d H:i:s

**解决方案** [如果你有解决方案，在这里清晰地阐述]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
详情页已增加，可在[demo](http://demo.go-admin.cn/admin)中看到。
