### ISSUE TITLE
[Question]How to selectively display data

### ISSUE THREAD

**Issue by tangy-ong** [GoAdminGroup/go-admin#116]
### Description [describe your questions]
目前发现数据库中数据很难自定义查询.  比如我现在需要显示商品table, 并且要FieldJoin到users表中,  只显示user_id=1所对应的全部商品.  但是发现默认会把所有的商品都显示出来, 就算FiledJoin了Users表, 但是并不会把 user_id!=1的商品过滤掉. 这个问题, 有更好的解决方案么?

**Comment by chenhg5** [comment]
@aColdCoder 预查询能不能解决你的问题？https://book.go-admin.cn/zh/admin-cha-jian/shu-ju-biao-ge/basic#yu-cha-xun

**Comment by gezichenshan** [comment]
@chenhg5 你好，请问什么是预查询？看了文档不是很懂。
然后我还看了文档说：
```
如果你单纯想增加一列，跟数据库字段不是一对一，可以使用这个API。
info.AddColumn(head string, fn FieldFilterFn)
```
这个AddColumn具体怎么表格中实现一对多的情况呢？

**Comment by gezichenshan** [comment]
@chenhg5 现在是这个项目不再维护了吗？
