### ISSUE TITLE
[Question]go-admin's table id looks not support for uuid

### ISSUE THREAD

**Issue by godcong** [GoAdminGroup/go-admin#119]
**问题描述** [详细地描述问题，让大家都能理解]
I tried many ways,  but can not insert an id with uuid string

**示例代码** [如果有必要，展示代码，线上示例，或仓库]
	cfg := table.DefaultConfig()
	cfg.PrimaryKey.Type = db.Varchar
	cfg.PrimaryKey.Name = "id"

	videosTable = table.NewDefaultTable(cfg)
        formList := videosTable.GetForm()
	formList.AddField("ID", "id", db.Varchar, form.Text).FieldNotAllowEdit().FieldNotAllowAdd()
//1.FieldDefault can display but can not insert
//2.SetInsertFn can not insert
//3.FieldValue do nothing
//4.add FieldHide remove FieldNotAllowAdd function can not insert

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by godcong** [comment]
i see the code SetInsertFn can do something before insert instance of default insert...
but i think some body like a function can do something before insert then use default insert...
```
// InsertDataFromDatabase insert data.
func (tb DefaultTable) InsertDataFromDatabase(dataList form.Values) error {
	if tb.form.Validator != nil {
		if err := tb.form.Validator(dataList); err != nil {
			return err
		}
	}

	if tb.form.InsertFn != nil {
		return tb.form.InsertFn(dataList)
	}

	if tb.form.BeforeInser!= nil {
		err := tb.form.BeforeInsert(dataList)
                if err != nil {
                    return err
                }
	}
```
i try to add the `BeforeInsert` function after `InsertFn` and before the default insert.
if you like this idea, i will create a pullrequest

**Comment by chenhg5** [comment]
@godcong Can you help me test with the lastest master version code?

**Comment by godcong** [comment]
now uuid inert and used ok
