### ISSUE TITLE
[Question]FieldNotAllowEdit FieldDefault can't used in same TableForm field

### ISSUE THREAD

**Issue by godcong** [GoAdminGroup/go-admin#120]
**问题描述** [详细地描述问题，让大家都能理解]
if i set `FieldDefault` with a random uuid.
after i post to add the table ,i change info with edit form page.
i can't commit the value.
because it will set a new default value with this field.

**示例代码** [如果有必要，展示代码，线上示例，或仓库]
```go
formList.AddField("VID", "vid", db.Text, form.TextArea).FieldDefault(uuid.NewV1().String()).FieldNotAllowEdit()
```

**Comment by chenhg5** [comment]
working on it

**Comment by godcong** [comment]
perhaps FieldNotAllowEdit() need some arguments to set ...
for example:
if i want to call `FieldDefault(uuid.NewV1().String())` on `Edit`, but not on `Add`.
when i add these two functions(`FieldNotAllowEdit()`,`FieldNotAllowAdd()`)
I can't control its works, which to used the default value

**Comment by godcong** [comment]
now i can add a default value without change it
