### ISSUE TITLE
[Question] Handling associations?

### ISSUE THREAD

**Issue by sandeepravi** [GoAdminGroup/go-admin#121]
### Description 

Is there any way to show associations of objects in the listing and details page? 

Like, I want to show the tags(table 1) associated with a product(table 2) in the Product listing page.

Is there a way to do this?

**Comment by chenhg5** [comment]
@sandeepravi  Do you mean join table query? https://book.go-admin.cn/en/admin-plugins/data-table/basic#join-table

**Comment by sandeepravi** [comment]
The join query helps in cases when we need to show the associated table's details - I looked into this.

But I just wanted to show the foreign key id (role_id) in the parent table and have it link to the details page of the associated table.

**Comment by chenhg5** [comment]
@sandeepravi The issue is too long and will be closed. The usage example of what you need can be found in the [demo](http://demo.go-admin.com/).
