### ISSUE TITLE
[BUG]form.Radio and form.SelectSingle sometimes can't update

### ISSUE THREAD

**Issue by godcong** [GoAdminGroup/go-admin#127]
### bug 描述 [详细地描述 bug，让大家都能理解]
i edit a table has a radio value with int(1,2)
when i update the table,sometimes was ok, sometime was failed
i debug the steps
sometimes the function getInjectValueFromFormValue filter the value
getInjectValueFromFormValue sometimes filter the default value

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
add a table like this:
```
	formList := nodeTable.GetForm()
	formList.SetPostHook(func(values form2.Values) error {
		log.Infow("post hook")
		return nil
	})
	formList.AddField("ID", "id", db.Int, form.Default).FieldNotAllowAdd().FieldNotAllowEdit()
	formList.AddField("SyncData", "sync", db.Tinyint, form.Radio).FieldDefault("2").
		FieldOptions([]map[string]string{
			{
				"field":    "sync",
				"label":    "async",
				"value":    "1",
				"selected": "",
			}, {
				"field":    "sync",
				"label":    "sync",
				"value":    "2",
				"selected": "checked",
			},
		})
```

### 期望结果 [描述你原本期望看到的结果]
update success

**Comment by godcong** [comment]
i have print out the dataList:
sync has two arguments:
```
sync:[1] sync[]:[]
```
if sync:[1] is after sync[]:[] updated ok
else was failed.

**Comment by godcong** [comment]
you can reproduce this exception on https://demo.go-admin.cn/admin/info/user/edit
![image](https://user-images.githubusercontent.com/2727298/71614908-4dbfa100-2be9-11ea-9b2f-25899ef445e3.png)

**Comment by chenhg5** [comment]
@godcong fixed. [#372daf](https://github.com/GoAdminGroup/go-admin/commit/372dafc7252d74040401ee464c4b08fdcc7aea82)

**Comment by godcong** [comment]
fixed runs ok
