### ISSUE TITLE
[BUG]Update data with a failed result on used an uuid

### ISSUE THREAD

**Issue by godcong** [GoAdminGroup/go-admin#135]
### bug 描述 [详细地描述 bug，让大家都能理解]
when i update a value, the page result an update error to me.
```
错误!
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'descbe16502-be00-4f9c-aa93-b25e0291d826 LIMIT ? OFFSET ?' at line 1
```

i see the edit page's _previous_ key the sort type displayed with a wrong value:
```
<input type="hidden" name="_previous_" value="/admin/info/globals?__page=1&amp;__pageSize=10&amp;__sort=id&amp;__sort_type=descbe16502-be00-4f9c-aa93-b25e0291d826">
```

the data uuid is : 1be16502-be00-4f9c-aa93-b25e0291d826
it looks splited the uuid and insert it into the _previous_
finally the value was updated successed.

- GoAdmin 版本: [e.g. 1.0.0]
1.1.6

**Comment by chenhg5** [comment]
Fixed. [#92bd01](https://github.com/GoAdminGroup/go-admin/commit/92bd010f9d5a2c778ad6a3c360e3418cdf56347a)
