### ISSUE TITLE
[BUG] 执行go get github.com/GoAdminGroup/go-admin@latest报错

### ISSUE THREAD

**Issue by git-ruoshui** [GoAdminGroup/go-admin#137]
### 按照说明执行 go get github.com/GoAdminGroup/go-admin@latest 
控制台提示   go: cannot use path@version syntax in GOPATH mode
 [详细地描述 bug，让大家都能理解]

### 版本信息:

- GoAdmin 版本: [1.16]
- golang 版本[1.13]
- 浏览器环境 [chrome78]
- 开发环境 [ win10]

**Comment by godcong** [comment]
go: cannot use path@version syntax in GOPATH mode
问题写得很清楚了啊...如果这个是bug的话,那就是golang的bug
