### ISSUE TITLE
[BUG]error：wrong id，No __goadmin_detail_pk parameter

### ISSUE THREAD

**Issue by laijinhang** [GoAdminGroup/go-admin#138]
### bug 描述
![image](https://user-images.githubusercontent.com/30384322/71956607-8b927a00-3226-11ea-8ae3-e399f9145d83.png)

authRoute.GET("/info/:__prefix", controller.ShowInfo)
controller.ShowInfo方法生成 edit、detail的url中没有__goadmin_detail_pk参数

### 版本信息:

- GoAdmin 版本: [e.g. 1.0.0]
1.1.6

**Comment by chenhg5** [comment]
@laijinhang 使用的是master版本吗？themes也要同步更新才行。

**Comment by godcong** [comment]
Fixed. #92bd01 & #096287 到这版本，我这OK

**Comment by godcong** [comment]
merge到最新版,页面点击edit图标,显示上面这个`wrong id`

**Comment by chenhg5** [comment]
> merge到最新版,页面点击edit图标,显示上面这个`wrong id`

themes也更到master了吗 @godcong

**Comment by godcong** [comment]
themes用的release版,我试下master

**Comment by godcong** [comment]
@chenhg5 是版本的问题,master可以了
详情页面也一样,要升级到master才行.
