### ISSUE TITLE
[BUG]Detail Page has some problems

### ISSUE THREAD

**Issue by godcong** [GoAdminGroup/go-admin#142]
### bug 描述 [详细地描述 bug，让大家都能理解]
1.  when entry the detail page, the task bar keep turning,never stopped.
2.  the edit in the detail page,response a `wrong id`
3. delete look not woking.

4. i entry the user permission page then save... the admin lost its permissions...

- GoAdmin 版本: [e.g. 1.0.0]
master
- Themes
master
- golang 版本
1.1.3

### 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/2727298/72132359-b2cd8080-33b9-11ea-9314-b0634918d4c5.png)

**Comment by godcong** [comment]
The background color is the `dark mode` that I opened on github plugins and has nothing to do with themes

**Comment by godcong** [comment]
the detail about 4
user permission was not displayed, and save will clear the permission
![image](https://user-images.githubusercontent.com/2727298/72132823-e4931700-33ba-11ea-8a27-e1ffef53a04a.png)

**Comment by chenhg5** [comment]
Fixed. [#1d8fc36](https://github.com/GoAdminGroup/go-admin/commit/1d8fc36d61c66dc1853acc8d597fad7d2721cdd3)
