### ISSUE TITLE
[Feature] 右侧滚动条滚动的时候，左侧菜单栏跟着一起滚动，体验略差

### ISSUE THREAD

**Issue by wangdy0909** [GoAdminGroup/go-admin#144]
### 版本信息:

- GoAdmin 版本: [最新demo]
- golang 版本
- 浏览器环境：chrome
- 开发环境 [windows]

### 其他信息 :
![image](https://user-images.githubusercontent.com/26474273/72197093-74d36980-3458-11ea-9796-ed3cb2f1fd92.png)

**Comment by chenhg5** [comment]
@wangdy0909 最新版本已增加顶部菜单按钮可设置固定侧边栏，并会使浏览器记住选择。
