### ISSUE TITLE
[Question] 筛选模块，模糊查询

### ISSUE THREAD

**Issue by laijinhang** [GoAdminGroup/go-admin#145]
**需求描述**
![image](https://user-images.githubusercontent.com/30384322/72198308-90de0780-3466-11ea-844f-c984c491cd32.png)
这边后期是否考虑做成模糊查询？

**Comment by laijinhang** [comment]
看到源码中有预留实现模糊查询代码，但是没有实现

**Comment by chenhg5** [comment]
@laijinhang 实现了的，有遇到问题吗

**Comment by laijinhang** [comment]
![image](https://user-images.githubusercontent.com/30384322/72199280-b8d46780-3474-11ea-832b-d9d8e7936428.png)
我看源码那边是用 = 查询的

**Comment by chenhg5** [comment]
@laijinhang 可以设置，像这样：https://github.com/GoAdminGroup/go-admin/blob/master/examples/datamodel/user.go#L34

**Comment by laijinhang** [comment]
试了下，可以。多谢
