### ISSUE TITLE
[BUG] Mysql 驱动 panic

### ISSUE THREAD

**Issue by xiaomi-tc** [GoAdminGroup/go-admin#146]
### bug 描述

**修改example下的config.json, 将驱动从‘sqlite‘ 改成 ‘mysql’:**

"database": {
  "default": {
  "host": "127.0.0.1",
  "port": "3306",
  "user": "root",
  "pwd": "xxxxx",
  "name": "godmin",
    "max_idle_con": 50,
    "max_open_con": 150,
    "driver": "mysql"
  }
},
"prefix": "admin",
"store": {
......

**编译后运行出panic：**

GoAdmin is now running.
Running in "debug" mode. Switch to "release" mode in production.

**panic: sql: unknown driver "mysql" (forgotten import?)**

goroutine 1 [running]:
github.com/GoAdminGroup/go-admin/modules/db.(*Mysql).InitDB.func1()
	/home/devuser/Golibs/src/github.com/GoAdminGroup/go-admin/modules/db/mysql.go:56 +0x365
sync.(*Once).doSlow(0xc00028e468, 0xc0002432f0)
	/usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
github.com/GoAdminGroup/go-admin/modules/db.(*Mysql).InitDB(0xc00028e460, 0xc000279950, 0x1083e8f, 0x5)
	/home/devuser/Golibs/src/github.com/GoAdminGroup/go-admin/modules/db/mysql.go:43 +0x8d
github.com/GoAdminGroup/go-admin/engine.(*Engine).InitDatabase(0xc000243d98, 0x0)
	/home/devuser/Golibs/src/github.com/GoAdminGroup/go-admin/engine/engine.go:87 +0x18d
github.com/GoAdminGroup/go-admin/engine.(*Engine).AddConfigFromJSON(0xc000243d98, 0x108ad07, 0xd, 0x4)
	/home/devuser/Golibs/src/github.com/GoAdminGroup/go-admin/engine/engine.go:71 +0xf5
main.main()
	/home/devuser/Golibs/src/github.com/GoAdminGroup/example/main.go:69 +0x255

### 期望结果 
 在 modules/db/drivers/mysql.go 的 import 中加入：
        
	_ "github.com/go-sql-driver/mysql"

重新编译就能运行起来了

### 版本信息:

- GoAdmin 版本:  1月10号最新下载
- golang 版本 1.13.5
- 浏览器环境
- 开发环境  centos7.7.1908

**Comment by chenhg5** [comment]
@xiaomi-tc https://book.go-admin.cn/zh/quick_start#main-go
