### ISSUE TITLE
[BUG] form.File 当没进行更新时,会自动把原数据覆盖为空字符串

### ISSUE THREAD

**Issue by tangy-ong** [GoAdminGroup/go-admin#147]
### bug 描述 [详细地描述 bug，让大家都能理解]
form.File 在进行编辑的更新的时候, 如果没有进行选择文件, 那么提交后, 会提交个空字符串, 并且还会更新到数据库, 把原数据覆盖为空.

### 版本信息:

- GoAdmin 版本: [e.g. 1.1.6]
- golang 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenhg5** [comment]
@aColdCoder 最新版本的GoAdmin吗 demo中的管理员编辑复现不出来你的问题

**Comment by aColdCoder** [comment]
https://demo.go-admin.cn/admin/info/user  在编辑的form表单里面, 当你增加个 Avatar 字段的  form.File,  然后每次编辑更新时,  只要你不重新选择图片, 那么就会把 数据库里的 覆盖为空

**Comment by chenhg5** [comment]
@aColdCoder 管理员编辑中的头像就是form.File，但是编辑未出现你说的覆盖掉的情况。

**Comment by chenhg5** [comment]
> https://demo.go-admin.cn/admin/info/user 在编辑的form表单里面, 当你增加个 Avatar 字段的 form.File, 然后每次编辑更新时, 只要你不重新选择图片, 那么就会把 数据库里的 覆盖为空

我知道了，我修复一下

**Comment by chenhg5** [comment]
Fixed. [#5340f7](https://github.com/GoAdminGroup/go-admin/commit/5340f7dbc2751e0e3cfb6cc69189c6db76fee223)
