### ISSUE TITLE
[BUG] 左上角,用户名展示会出现错误组件

### ISSUE THREAD

**Issue by tangy-ong** [GoAdminGroup/go-admin#148]
### bug 描述 [详细地描述 bug，让大家都能理解]
在页面左上角的用户名展示, 会出现不可预知的组件,  详细请查看图

### 版本信息:

- GoAdmin 版本: [e.g. 1.1.6]
- golang 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

### 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/20501751/72213106-fe9c3900-3523-11ea-944e-b58adbb6228b.png)

**Comment by chenhg5** [comment]
@aColdCoder 手机端？

**Comment by chenhg5** [comment]
时间太久，且无法复现，先关闭。
