### ISSUE TITLE
[Proposal] 自定义handler数据读取

### ISSUE THREAD

**Issue by tangy-ong** [GoAdminGroup/go-admin#150]
**需求描述** [详细地描述需求，让大家都能理解]

使用InfoPanel定义数据的显示格式和页面组件,  但是数据读取的部分, 可否提供接口, 让用户自己去数据库进行读取, 用户只需要返回预先infoPanel定义好的 数据字段格式的数据即可.  例如GetDataFromDatabase 这类的方法,能否提供出来,  并且 最好是能把 handler的上下文 ctx  传递过来. 

最好是, 框架能把页面组件组装方式  和  数据的读取方式 解耦分离. 如果简单的业务, 可以使用目前已经提供好的数据读取方式, 但是复杂的业务, 也能提供用户自定义的读取方式.

**解决方案** [如果你有解决方案，在这里清晰地阐述]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
#128

**Comment by chenhg5** [comment]
Duplicate of #128
