### ISSUE TITLE
[Proposal]Admin 知道账号密码就能登录，如何让数据更安全

### ISSUE THREAD

**Issue by yueqianzhang** [GoAdminGroup/go-admin#152]
**需求描述** [详细地描述需求，让大家都能理解]
Admin 知道账号密码就能登录，如何让数据更安全
**解决方案** [如果你有解决方案，在这里清晰地阐述]
增加两步认证，或者 oauth
**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
已经在计划中的，未来两个版本会推出
