### ISSUE TITLE
参照goAdmin示例，调用NewAdmin时报错

### ISSUE THREAD

**Issue by zhaoran025** [GoAdminGroup/go-admin#153]
undefined: Generators 找不到Generators
main.go 文件如下
package main

import (
	_ "github.com/GoAdminGroup/go-admin/adapter/gin" // 必须引入，如若不引入，则需要自己定义
	"github.com/GoAdminGroup/go-admin/engine"
	"github.com/GoAdminGroup/go-admin/modules/config"
	_ "github.com/GoAdminGroup/go-admin/modules/db/drivers/mysql"
	"github.com/GoAdminGroup/go-admin/modules/language"
	"github.com/GoAdminGroup/go-admin/plugins/admin"
	_ "github.com/GoAdminGroup/themes/adminlte" // 必须引入，不然报错
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()
	eng := engine.Default()
	cfg := config.Config{
		Databases: config.DatabaseList{
			"default": {
				Host:       "127.0.0.1",
				Port:       "3306",
				User:       "root",
				Pwd:        "123456",
				Name:       "test",
				MaxIdleCon: 50,
				MaxOpenCon: 150,
				Driver:     config.DriverMysql,
			},
		},
		UrlPrefix: "admin", // 访问网站的前缀
		// Store 必须设置且保证有写权限，否则增加不了新的管理员用户
		Store: config.Store{
			Path:   "./uploads",
			Prefix: "uploads",
		},
		Language: language.CN,
	}

	adminPlugin := admin.NewAdmin(Generators)

	// 也可以调用 AddGenerator 方法加载
	// adminPlugin.AddGenerator("user", GetUserTable)
	eng.AddConfig(cfg).
		AddPlugins(adminPlugin).  // 加载插件
		Use(r)

	r.Run(":9033")
}
table.go 文件如下
package main

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "users" => http://localhost:9033/admin/info/users
//
var Generators = map[string]table.Generator{
	"users": GetUsersTable,
}

**Comment by chenhg5** [comment]
go run .
