### ISSUE TITLE
[Question]初始admin登录，登录失败

### ISSUE THREAD

**Issue by yueqianzhang** [GoAdminGroup/go-admin#155]
**问题描述** [详细地描述问题，让大家都能理解]
初始Admin账号密码，登录失败，debug发现，读入的账号和密码都为空
**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]
现在在公司，如果需要，晚点回去贴代码

**Comment by chenhg5** [comment]
@yueqianzhang 什么版本的GoAdmin，以及浏览器，方便告诉下吗

**Comment by yueqianzhang** [comment]
Mac 目前最新 Chrome 64 位
GoAdmin 1.1.7
不知道是不是代码的问题..
![image](https://user-images.githubusercontent.com/20694300/72728377-2e081100-3bc8-11ea-8526-8c98a6367ca4.png)

**Comment by xifengzhu** [comment]
应该是没有创建表 `goadmin_users`
