### ISSUE TITLE
[Question]几个问题请教一下。

### ISSUE THREAD

**Issue by zhaoran025** [GoAdminGroup/go-admin#158]
**问题描述** [详细地描述问题，让大家都能理解]
1.如何指定字段排序？
info.SetSortAsc()，是默认按主键排序吗?
2.预查询,日期字段查询怎么做?

**示例代码** [如果有必要，展示代码，线上示例，或仓库]
`1.
info.SetSortAsc("trade_date") error，
info.AddField("交易日期","trade_date", db.Date).FieldSortable(true) error
2.
info.Where("trade_date","=","2020-10-10") error`
**其他信息** [如截图等其他信息可以贴在这里]

**Comment by zhaoran025** [comment]
能否将sql打印到控制台，方便调试

**Comment by chenhg5** [comment]
@zhaoran025 全局配置中可以设置。https://book.go-admin.cn/zh/quick_start#quan-ju-pei-zhi-xiang-shuo-ming
