### ISSUE TITLE
[Proposal] 添加数据权限

### ISSUE THREAD

**Issue by sanrentai** [GoAdminGroup/go-admin#160]
**需求描述** [详细地描述需求，让大家都能理解]

增加人员等级，比如等级为1的人，可以看等级大于1的人的所有数据，在建立数据时，增加相关等级的设置.
全部数据权限 无数据权限限制
本级数据权限 限制只能看到本部门数据
自定义数据权限 可根据实际需要选择部门控制数据权限

**解决方案** [如果你有解决方案，在这里清晰地阐述]

可以参考 https://docs.auauz.net/guide/hdsc.html#%E6%95%B0%E6%8D%AE%E6%9D%83%E9%99%90

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
@sanrentai 当前的rbac权限管理可以实现你的需求。目前权限的设计还会继续改进，使得更容易上手。
