### ISSUE TITLE
[Proposal] Support multi files upload operation

### ISSUE THREAD

**Issue by tangy-ong** [GoAdminGroup/go-admin#161]
**需求描述** [详细地描述需求，让大家都能理解]
1. form.file组件, 只能让用户选择一张图片.  能否出一个能让用户上传多张图片的组件. 类似于:
![image](https://user-images.githubusercontent.com/20501751/73416659-89689a80-4350-11ea-9a8f-4ccdc55e7eec.png)
2. 富文本 在进行插入图片的时候, 只能插入网上的链接图片.  能否让用户可以选择本地图片. 也就是说, 选择一个功能更加丰富的富文本组件. 
**解决方案** [如果你有解决方案，在这里清晰地阐述]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
新版本中已解决。
