### ISSUE TITLE
[Question] 访问出现302状态码

### ISSUE THREAD

**Issue by hzcool** [GoAdminGroup/go-admin#166]
### 问题描述 [详细地描述问题，让大家都能理解]
运行成功后访问/admin/login ， 出现一连串302错误
### 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/39079637/74130060-20b8d200-4c1c-11ea-9f8c-b0933b316e07.png)

![image](https://user-images.githubusercontent.com/39079637/74119933-78474580-4bfc-11ea-8a61-37b37c5948bd.png)

![image](https://user-images.githubusercontent.com/39079637/74129997-ebac7f80-4c1b-11ea-86e3-be51be971c21.png)

![image](https://user-images.githubusercontent.com/39079637/74130085-39c18300-4c1c-11ea-970b-5e8a0cade8de.png)

**Comment by chenhg5** [comment]
问题较久，且无法重现。先关闭。
