### ISSUE TITLE
[Proposal]能否把goadmin的用户表与普通用户表合二为一？

### ISSUE THREAD

**Issue by lujscn** [GoAdminGroup/go-admin#168]
### 需求描述 [详细地描述需求，让大家都能理解]
目前我的网站前台一个用户体系，后台goadmin又是另一个用户体系。能否把这两个用户体系合并在一起？

### 解决方案 [如果你有解决方案，在这里清晰地阐述]
goadmin可以自定义用户表名称，网站前台的注册用户表和goadmin后台用户表使用同一张表。
网站前台注册用户默认没有权限登录goadmin，如果管理员给予登录goadmin后台的权限后，这个用户就可以用他注册的账号直接登录goadmin后台。

**Comment by chenhg5** [comment]
@lujscn 最新版本可以实现。需要以下几个步骤：
