### ISSUE TITLE
[BUG]同一个package下生成多个table时，会覆盖原有的table.go

### ISSUE THREAD

**Issue by KaiwenWang** [GoAdminGroup/go-admin#169]
### bug 描述 [详细地描述 bug，让大家都能理解]
同一个package下生成多个table时，会覆盖原有的table.go
### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
比如service package 下，先生成user\order\shop\product代码，再生成ad，然后table.go中就只有ad的代码了
### 期望结果 [描述你原本期望看到的结果]
自动append代码，避免每次都去修改
### 版本信息:

- GoAdmin 版本: [e.g. 1.0.0]
- golang 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenhg5** [comment]
最新版本cli 已修复此问题。
