### ISSUE TITLE
[Proposal] 有些方法太长，不利于复用，建议拆分一下

### ISSUE THREAD

**Issue by KaiwenWang** [GoAdminGroup/go-admin#170]
### Description [describe your advice]
有些方法太长，不利于复用

举例子：

**plugin/admin/modules/table/table.go** 下
```
func (tb DefaultTable) getDataFromDatabase
```
从800多行跨度到1200多行

再比如，该方法中，1190行 queryCmd 执行结束后，可以可以立刻返回，后续构造模板的逻辑，可以单独在外面包装一个方法。
```
res, err := connection.QueryWithConnection(tb.connection, queryCmd, args...)

if err != nil {
	return PanelInfo{}, err
}
```

### Solution [if any solutions, describe here]
golang一般的代码审计工具，审计不出这种问题。建议拆分下上述代码

### Others [screenshots and other info]
另外，虽然Golang 使用比较灵活，但是有些企业级开发中的代码规范建议参考一下：
1. 一个func 不要超过50行，超过说明逻辑拆分有问题，而且也不利于写单测
2. 代码中不要出现for\if 层层嵌套，会到导致圈复杂度过高。所以的bug\漏洞，往往出现在这种负责嵌套逻辑中。比较推崇的一个做法是，一个方法内部，缩进不要超过3层
3. 常用的变量字符串，改写成常量，比如代码中的. goadmin等字符串，代码中多处存在，建议维护一个types包专门维护这些内容，免得将来出现变化时到处改动代码

先说这些吧，希望这个项目越来越好

**Comment by chenhg5** [comment]
@KaiwenWang 很好的建议，感谢。代码和架构会逐步优化，确实存在有很多考虑不周的问题。如果遇到，欢迎指出。🙏
