### ISSUE TITLE
[Proposal]希望go-admin的权限管理可以支持通过用户ID验证而不用获取用户对象

### ISSUE THREAD

**Issue by lujscn** [GoAdminGroup/go-admin#171]
### 需求描述 [详细地描述需求，让大家都能理解]
go-admin的权限管理挺好的，有很多业务不是在go-admin的如果也能用上这个权限管理就好了。

### 解决方案 [如果你有解决方案，在这里清晰地阐述]
比如说，任意非go-admin的页面，可以用如下方法使用
```
        // 验证 用户ID 是否有 dashboard 权限
        if !CheckPermission("dashboard",用户ID) {
            return "没有权限" 
        }

        // 验证角色ID 是否有 operator 权限
        if !CheckRole("operator",角色ID) {
            return "没有权限" 
        }
```
### 其他信息 [如截图等其他信息可以贴在这里]
![1](https://user-images.githubusercontent.com/5188727/74909567-8d3d8900-53f3-11ea-9d4a-ab0eb503ceac.png)

**Comment by chenhg5** [comment]
@lujscn 不是可以用吗

**Comment by lujscn** [comment]
> 
> 
> @lujscn 不是可以用吗

您的官方文档上是要传入用户而不是一个数字ID啊，如果是在其它地方用，就不好传入用户啊

**Comment by chenhg5** [comment]
> > @lujscn 不是可以用吗
> 
> 您的官方文档上是要传入用户而不是一个数字ID啊，如果是在其它地方用，就不好传入用户啊

@lujscn 

可以的，用法如下：

```go
import (
      ...
      github.com/GoAdminGroup/go-admin/plugins/admin/models
      ...
)

func XXX() {
      var userId int = "1"
      user := models.UserWithId(userId).WithRoles().WithPermissions()
      // 验证角色
      user.CheckRole("")
      // 验证权限
      user.CheckPermission("")
      // 等等
}

```

**Comment by lujscn** [comment]
好的，非常感谢
