### ISSUE TITLE
[BUG] 筛选form.Select 不生效 以及 时间字段为bigint筛选问题 

### ISSUE THREAD

**Issue by smirkcat** [GoAdminGroup/go-admin#174]
#### 1. **按照例子**

```go
// 设置为单选类型
info.AddField("Gender", "gender", db.Tinyint).
    FieldFilterable(types.FilterType{FormType: form.SelectSingle}).
    FieldFilterOptions([]map[string]string{
        {"value": "0", "field": "men"},
        {"value": "1", "field": "women"},
    }).FieldFilterOptionExt(map[string]interface{}{"allowClear": true})
```

把 ```form.SelectSingle``` 改为 ```form.Select``` 无法实现筛选，单个筛选也不行

####  2. **时间筛选** 

数据库时间字段为 ```bigint``` 无法用时间筛选，请问怎么实现

### 版本信息:

- GoAdmin 版本: [e.g. 1.0.0]
- golang 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenhg5** [comment]
@smirkcat 复现不了，确认下你的GoAdmin版本是不是最新的。

**Comment by smirkcat** [comment]
@chenhg5 
版本信息:

    GoAdmin 版本:  1.2.2
    golang 版本 go version go1.13.6 windows/amd64
    浏览器环境 各个浏览器
    开发环境 windows vscode

**Comment by smirkcat** [comment]
@chenhg5 
筛选url为
http://18.139.250.215:9033/admin/info/localorder?pair=&username=&username__operator__=like&order_number=&status=&type=buy&hegding_status[]=0&hegding_status[]=1&create_time_start__goadmin=&create_time_end__goadmin=&_previous_=&_t=
其中 hegding_status 为筛选的字段

**Comment by chenhg5** [comment]
@smirkcat 

方便提供下数据模型文件中，```hegding_status```这一列的代码吗？

**Comment by smirkcat** [comment]
```golang
info.AddField("对冲状态", "hegding_status", db.Tinyint).FieldDisplay(func(model types.FieldModel) interface{} {
		if model.Value == "2" {
			return "状态3"
		}
		if model.Value == "1" {
			return "状态2"
		}
		return "状态1"
	}).FieldFilterable(types.FilterType{FormType: form.Select}).
		FieldFilterOptions([]map[string]string{
			{"value": "0", "field": "状态1"},
			{"value": "1", "field": "状态2"},
			{"value": "2", "field": "状态3"},
		})
```

**Comment by chenhg5** [comment]
@smirkcat 

测试了下，```form.Select```目前确实不支持的，改成```form.SelectSingle```可以。
```form.Select```本周的下个版本应该会增加支持。

**Comment by chenhg5** [comment]
当前版本已支持。
