### ISSUE TITLE
[Question] 编辑行数据 wrong id 但是可以删除

### ISSUE THREAD

**Issue by smirkcat** [GoAdminGroup/go-admin#175]
### 问题描述 [详细地描述问题，让大家都能理解]
编辑行数据 出现 wrong id  但是可以删除

疑问不知道是不是自己配置错了 还是什么 所以我想问下什么情况下会报这个错误，主要是测试了删除功能，添加功能都正常 id 主键是bigint 配置我也设置了 bigint

### 其他信息 [如截图等其他信息可以贴在这里]
版本号 1.2.2

**Comment by chenhg5** [comment]
@smirkcat 能不能提供下重现步骤 其他表正常吗 还是只有设置 bigint 的这个表不行

**Comment by smirkcat** [comment]
我想我知道问题了 
/admin/info/123/edit?__page=1&__pageSize=10&__sort=id&__sort_type=desc&id=1
这是编辑url 
最后不应该是id=1吧
我以为是浏览器缓存问题 清空了 id字段也没变
然后换浏览器也有问题，不知道怎么设置 我是从老版本直接修改升级上来的
我把url中的 id 手动改为 __goadmin_edit_pk
/admin/info/123/edit?__page=1&__pageSize=10&__sort=id&__sort_type=desc&__goadmin_edit_pk=1
然后就运行正常了

所以该怎么解决

**Comment by chenhg5** [comment]
@smirkcat theme 版本是多少 更到最新了吗

**Comment by smirkcat** [comment]
@chenhg5 

oh ... 升级了 解决 抱歉打扰了
