### ISSUE TITLE
[BUG] types.FormPanel.FieldOptions() item "selected": "selected"  invalid

### ISSUE THREAD

**Issue by sinlov** [GoAdminGroup/go-admin#176]
### Bug Description [describe the bug in detail]
types.FormPanel.FieldOptions() item "selected": "selected"  invalid
Not selected item when `formList` when before `form.SelectSingle` UI, must click item to select.
### How to reproduction [describe the steps how to reproduce the bug]
use from list code as old version as will.
### Expect [describe your expect result]
selected item when `formList` at `form.SelectSingle`
### Reproduction code [here to show your codes or examples]
```go
formList.AddField("Activation", "activation", db.Integer, form.SelectSingle).
FieldOptions([]map[string]string{
		{
			"field":    "yes",
			"value":    "1",
			"selected": "selected",
		},
		{
			"field": "no",
			"value": "0",
			"selected": "",
		},
	})
```

### Versions
```conf
go 1.13

require (
	github.com/GoAdminGroup/go-admin v1.2.2
	github.com/GoAdminGroup/themes v0.0.23
)
```

- GoAdmin version: [1.2.2]
- golang version: [go version go1.13.6 darwin/amd64]
- Browser [chrome 79.0.3945.130]
- OS [mac OS]

**Comment by chenhg5** [comment]
@sinlov Fixed. [#442c29](https://github.com/GoAdminGroup/go-admin/commit/442c2919fe5ee842b742053307dcd6ce331fd114)

**Comment by sinlov** [comment]
@chenhg5 use
github.com/GoAdminGroup/go-admin v1.2.3-0.20200223082159-442c2919fe5e
not fix

**Comment by sinlov** [comment]
fix version
- github.com/GoAdminGroup/go-admin v1.2.4
