### ISSUE TITLE
[BUG] bee.aoscdn.com:ComposeHtml Error:template: comp:98: function "render" not defined

### ISSUE THREAD

**Issue by harry0703** [GoAdminGroup/go-admin#177]
### bug 描述 [详细地描述 bug，让大家都能理解]

Request Method: | GET
-- | --
Request URL: | /admin/
RemoteAddr: | 127.0.0.1

Stack
/usr/local/go/src/runtime/panic.go:679
/Users/harry/go/src/bee.aoscdn.com/vendor/github.com/GoAdminGroup/go-admin/template/components/composer.go:31
/Users/harry/go/src/bee.aoscdn.com/vendor/github.com/GoAdminGroup/go-admin/template/components/table.go:48
/Users/harry/go/src/bee.aoscdn.com/vendor/github.com/GoAdminGroup/go-admin/examples/datamodel/content.go:95
/Users/harry/go/src/bee.aoscdn.com/main.go:82
/Users/harry/go/src/bee.aoscdn.com/vendor/github.com/GoAdminGroup/go-admin/adapter/beego/beego.go:121
/Users/harry/go/src/bee.aoscdn.com/vendor/github.com/GoAdminGroup/go-admin/engine/engine.go:82
/Users/harry/go/src/bee.aoscdn.com/main.go:81
/Users/harry/go/src/bee.aoscdn.com/vendor/github.com/astaxie/beego/router.go:769
/usr/local/go/src/net/http/server.go:2802
/usr/local/go/src/net/http/server.go:1890
/usr/local/go/src/runtime/asm_amd64.s:1357

### 版本信息:

- GoAdmin 版本: [e.g. 1.0.0]
- golang 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenhg5** [comment]
@harry0703 确认一下 GA 版本和 theme 版本是不是最新
