### ISSUE TITLE
[Proposal] 建议前后端分离，方便业务拆分。

### ISSUE THREAD

**Issue by forging2012** [GoAdminGroup/go-admin#182]
### 需求建议 ：
使用流行的主流vue、React框架开发前端，实现前后端分离。
利于业务拆分。

**Comment by jiafuzhang** [comment]
想要一个vue版本的

**Comment by westfly** [comment]
https://github.com/wenjianzhang/go-admin 
找到 一个 同名的，前后端分离的。

**Comment by cppfuns** [comment]
看具体业务吧，对于我就不希望前后端分离，因为我需要资源都在一个程序里，方便部署以及加密方面的考虑
