### ISSUE TITLE
[BUG] 默认头像引起的https问题

### ISSUE THREAD

**Issue by ma6254** [GoAdminGroup/go-admin#184]
### bug 描述 [详细地描述 bug，让大家都能理解]

使用默认头像时，用chrome浏览器打开页面，左上角显示不不安全

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

使用默认头像、使用chrome打开

### 期望结果 [描述你原本期望看到的结果]

无该报警信息

### 复现代码 [提供可复现的代码，仓库，或线上示例]

使用<https://github.com/GoAdminGroup/example>原封不动，且将站点部署为https

### 版本信息:

- GoAdmin 版本：4859212fb5f2c6ae7ac865c2e79dfdc4807d7ee9  
- golang 版本：	go version go1.13.4 linux/amd64
- 浏览器环境：Google Chrome 已是最新版本 版本 80.0.3987.132（正式版本） （64 位）
- 开发环境：Win10 Vscode

### 其他信息 [如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/12112251/76432917-93b99200-63ee-11ea-8bd6-757578daef5f.png)

![image](https://user-images.githubusercontent.com/12112251/76432982-a59b3500-63ee-11ea-8a4e-2d0d561d9cc7.png)

**Comment by chenhg5** [comment]
已修复。[7d4504](https://github.com/GoAdminGroup/example/commit/7d450436414e565a65fc3ddb442f7628a7e3c30a)
