### ISSUE TITLE
[BUG]创建新用户上传头像后登陆发现头像加载失败

### ISSUE THREAD

**Issue by xc70203** [GoAdminGroup/go-admin#190]
### bug 描述 [详细地描述 bug，让大家都能理解]
创建新用户成功上传头像后，用新账号重新登录后发现头像加载失败。

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1. 创建新用户并上传头像
2. 退出admin账号，使用新用户账号登录
3. 新用户成功登录后，发现头像加载失败
查看源码<img src="/uploads/206c3c64-2575-4f45-b515-b2300c26de8a.jpg" class="img-circle" alt="User Image">，头像文件也在<project>/uploads中，但加载失败，浏览器显示：

GET http://192.168.3.111/uploads/206c3c64-2575-4f45-b515-b2300c26de8a.jpg 404 (Not Found)

### 期望结果 [描述你原本期望看到的结果]
正确加载创建账号时上传的头像。

### 版本信息:

- GoAdmin 版本：v1.2.5
- golang 版本：1.14
- 浏览器环境：QQ浏览器10.5.2（3863）
- 开发环境：win10

**Comment by chenhg5** [comment]
@xc70203 确认一下：

1. 文件是否已经上传成功
2. web框架中是否有加上对uploads下静态文件的请求处理，如：https://github.com/GoAdminGroup/go-admin/blob/master/examples/gin/main.go#L92

**Comment by xc70203** [comment]
是我的问题。我用的iris框架，忘记写入：
app.HandleDir("/uploads", "./uploads", iris.DirOptions{
		IndexName: "/index.html",
		Gzip:      false,
		ShowList:  false,
})
写入后问题解决。
