### ISSUE TITLE
[Proposal] too many repo code depends on plugin admin, it is a bad design

### ISSUE THREAD

**Issue by KaiwenWang** [GoAdminGroup/go-admin#191]
### Bug Description [describe the bug in detail]
too many repo code depends on plugin admin, it is a bad design.
some case in modules and template
### Versions

- GoAdmin version: [e.g. 1.0.0]
- golang version
- Browser
- OS [e.g. mac OS]

**Comment by KaiwenWang** [comment]
If Plugin Admin is the core module, please make it not a plugin but a common model, maybe named base frame.  In common, plugin is just a impl of the plugin defined interface.

**Comment by chenhg5** [comment]
@KaiwenWang Yes, what you pointed out is indeed a place needs improving. Admin plugin contains some basic functions or modules which are dependent on other basic modules of the framework. For now, the Admin plugin is needed when running the framework. I will reconsider the design of the Admin plugin. Thanks.
