### ISSUE TITLE
[Question] After insert or update

### ISSUE THREAD

**Issue by davidlcarrascal** [GoAdminGroup/go-admin#193]
### Description [describe your questions]

Is there a way to get the data after an insert or update in a table? 
Some operations require updating cache or third party services.

**Comment by chenhg5** [comment]
@davidlcarrascal use API ```formList.SetPostHook``` https://github.com/GoAdminGroup/go-admin/blob/master/template/types/form.go#L894

**Comment by davidlcarrascal** [comment]
Thanks @chenhg5!! It's works for me 👍🏻
