### ISSUE TITLE
[Question] Error to import the example sql data in a postgresql db

### ISSUE THREAD

**Issue by davidlcarrascal** [GoAdminGroup/go-admin#194]
### Bug description [describe the bug in detail for everyone to understand]
 When importing [test sql data](https://raw.githubusercontent.com/GoAdminGroup/go-admin/master/data/admin.pgsql
)  in a Heroku postgresql database, I get the error: 

`ERROR:  syntax error at or near "1"
LINE 284: 1 0 1 2 Admin \N fa-tasks  2019-09-10 00:00:00 2019-09-10 00...`

**Comment by chenhg5** [comment]
@davidlcarrascal What is the command you use when importing the sql?

**Comment by davidlcarrascal** [comment]
@chenhg5 I did not execute any command. I copied the full file and execute it on a query.

**Comment by chenhg5** [comment]
@davidlcarrascal You should use ```psql``` to import. The command looks like: 
 ```
psql -p 5433 -d goadmin -U postgres -f ./admin.psql
```

**Comment by davidlcarrascal** [comment]
@chenhg5 Yeah! That works!
