### ISSUE TITLE
[Question] table必须要有主键吗

### ISSUE THREAD

**Issue by xiaoweihong** [GoAdminGroup/go-admin#198]
### 问题描述 [详细地描述问题，让大家都能理解]
业务表必须需要主键id吗？联合主键是否支持呢
### 示例代码 [如果有必要，展示代码，线上示例，或仓库]
 pq: column faces.id does not exist

**Comment by chenhg5** [comment]
@xiaoweihong 是的，你也可以自定义数据源。

**Comment by xiaoweihong** [comment]
好的
