### ISSUE TITLE
[Question]显示格式及查询问题

### ISSUE THREAD

**Issue by yueqianzhang** [GoAdminGroup/go-admin#200]
### 问题描述 [详细地描述问题，让大家都能理解]
1. infoPannel 显示的小数和日期能格式化吗？没找到相关文档
2. FieldJoin 能关联3个表查询吗一个字段吗（我的场景：设备表有属于的工厂ID，工厂表有工厂名，记录表有设备ID。我要把记录表设备ID在管理端显示成工厂名）？如果不能有没有什么其他的方式

感谢！！！

**Comment by chenhg5** [comment]
@yueqianzhang 目前暂时关联不了三个表。1，2都可以通过这个API解决：https://book.go-admin.cn/zh/admin-cha-jian/shu-ju-biao-ge/basic#xiu-gai-xian-shi-shu-chu

**Comment by yueqianzhang** [comment]
ok 谢谢
