### ISSUE TITLE
[Question]运行example下的gin 示例代码，会报【cannot use "github.com/GoAdminGroup/go-admin/template".DefaultFuncMap】错误，这个是有哪些库没安装或者引入吗？

### ISSUE THREAD

**Issue by laizhenxing** [GoAdminGroup/go-admin#201]
cannot use "github.com/GoAdminGroup/go-admin/template".DefaultFuncMap (type func() "html/template".FuncMap) as type "html/template".FuncMap in argument to "html/template".New("chart-legend").Funcs

**Comment by chenhg5** [comment]
@laizhenxing 更多问题可以在[example](https://github.com/GoAdminGroup/example)仓库下提问。这里先关闭。
