### ISSUE TITLE
[Question] 看了文档还是不懂怎么用

### ISSUE THREAD

**Issue by fghjhuang** [GoAdminGroup/go-admin#208]
### 问题描述 [详细地描述问题，让大家都能理解]
1. 下载项目源码放好gopath下
2. 不知道如何关联自己新建的用户表
3. 不知道如何监听登录状态和验证用户名密码是否正确然后跳转
4. 导入了demo的sql数据库，使用adm genarate 好像只能选择不是goadmin_xxx开头的表，如果自己建了一个表是users，就可以选择(如果是goadmin_users 是不会出现这个表让你选择的)，但是使用的时候提示找不到goadmin.goadmin_users表，只能把表名又改成goadmin_users,
### 示例代码 [如果有必要，展示代码，线上示例，或仓库]
`e := echo.New()
	
	eng := engine.Default()
	
	cfg := config.Config{
		Databases: config.DatabaseList{
			"default": {
				Host:       "127.0.0.1",
				Port:       "3306",
				User:       "huangst_admin",
				Pwd:        "xxxxxxx",
				Name:       "goadmin",
				MaxIdleCon: 50,
				MaxOpenCon: 150,
				Driver:     config.DriverMysql,
			},
			
		},
		Title:"smartG4New",
		LoginTitle: "smartG4New",
		UrlPrefix: "admin",
		IndexUrl:  "/",
		Store: config.Store{
			Path:   "./uploads",
			Prefix: "uploads",
		},
		Debug:    true,
		Language: language.CN,
	}
	
	 if err := eng.AddConfig(cfg).
		 AddGenerators(admin.Generators).
		Use(e); err != nil {
		panic(err)
	}
	// Start server
	go e.Logger.Fatal(e.Start(":999"))
	
	quit := make(chan os.Signal)
	signal.Notify(quit, os.Interrupt)
	<-quit
	log.Print("closing database connection")
	eng.MysqlConnection().Close()`
### 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/15012060/78112971-9463a800-7431-11ea-88bd-7d7d9a54a9e6.png)

**Comment by fghjhuang** [comment]
开发环境：windows 10 + goland ide + go 1.11

**Comment by chenhg5** [comment]
@fghjhuang https://segmentfault.com/a/1190000022215579 看一下这篇文章

**Comment by fghjhuang** [comment]
看懂怎么用了，谢谢！
