### ISSUE TITLE
[BUG]点击仪表盘，显示404 not found

### ISSUE THREAD

**Issue by luojc0517** [GoAdminGroup/go-admin#210]
### bug 描述 [详细地描述 bug，让大家都能理解]
点击仪表盘，显示404 not found

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1.使用示例中的gin框架
2.go run main.go
3.登录
4.点击仪表盘

### 期望结果 [描述你原本期望看到的结果]
正常显示仪表盘

### 复现代码 [提供可复现的代码，仓库，或线上示例]
[快速开始](https://book.go-admin.cn/zh/quick_start)
### 版本信息:

- GoAdmin 版本：v1.2.7
- golang 版本：go version go1.14.1 darwin/amd64
- 浏览器环境：Google Chrome 版本 80.0.3987.132（正式版本） （64 位）
- 开发环境：macOS Mojave 10.14.5

**Comment by chenhg5** [comment]
@luojc0517 新版本中，使用：```adm init -l cn``` 命令新建起步项目模板。
