### ISSUE TITLE
[BUG]undefined: Generators

### ISSUE THREAD

**Issue by luojc0517** [GoAdminGroup/go-admin#212]
### bug 描述 [详细地描述 bug，让大家都能理解]
自定义插件后go run main.go
undefined: Generators
### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1.参照[Admin插件使用](https://book.go-admin.cn/zh/cha-jian/admin)
2.adb generate
3.生成一个文件夹adm
4.adm中包含生成的表对应的xxx.go
5.修改main.go，开放`AddGenerators(Generators).  // 加载插件`这一行
### 期望结果 [描述你原本期望看到的结果]
期望正常运行并可访问自己插件的表数据
### 复现代码 [提供可复现的代码，仓库，或线上示例]
[快速开始](https://book.go-admin.cn/zh/quick_start)
### 版本信息:

- GoAdmin 版本：v1.2.7
- golang 版本：go version go1.14.1 darwin/amd64
- 浏览器环境：Google Chrome 版本 80.0.3987.132（正式版本） （64 位）
- 开发环境：macOS Mojave 10.14.5

### 其他信息 [如截图等其他信息可以贴在这里]
```
# command-line-arguments
./main.go:51:17: undefined: Generators
```

**Comment by chenhg5** [comment]
@luojc0517 https://segmentfault.com/a/1190000022215579

**Comment by Julyyq** [comment]
文档这块和example代码不是很一致，example代码中，import自定义model的是这句：`"github.com/GoAdminGroup/go-admin/examples/datamodel"`,  main函数中注册：`AddGenerators(Generators).`，这样会报`undefined: Generators`错误，应该改为`AddGenerators(datamodel.Generators).`。
```
go version go1.14.3 darwin/amd64。
```
