### ISSUE TITLE
[Announcement] GoAdmin Forum is now online!! 🎉🎉

### ISSUE THREAD

**Issue by chenhg5** [GoAdminGroup/go-admin#214]
After a day-night working, I am excited to tell you that [GoAdmin Forum](http://discuss.go-admin.com/) is now online. However, just a little content in there for now. I will keep writing more and do some guides and more significant work making the community better.
This is a milestone. It will be better. 

Thanks for everyone who helps.
Hope we can enjoy coding and build a better community together.

**Entrance of the forum categories:** 

- [Announcements](http://discuss.go-admin.com/t/about-the-announcements-category/11)
- [Getting Help](http://discuss.go-admin.com/c/Post-your-questions-or-problems-here-were-going-to-offer-help/7/none)
- [Proposal](http://discuss.go-admin.com/c/Any-proposals-about-GoAdmin-here/11/none)
- [Tips, Tricks, and How-To](http://discuss.go-admin.com/c/Share-your-examples-demos-and-guides-to-help-community-grow/6/none)
- [Golang](http://discuss.go-admin.com/c/Discussions-about-technical-designs-and-implementations-of-Gogs/8)

---

经过日夜工作，[GoAdmin论坛](http://discuss.go-admin.com/)终于上线了。虽然现在的内容不多，但后面会不断增加新的内容，包括一些指引和其他有意义的帮助信息，从而让我们的社区更好。
这是一个里程碑，感谢所有付出努力的人。

以下是一些板块的入口：

- [通告板块](http://discuss.go-admin.com/t/about-the-announcements-category/11)
- [中文求助板块](http://discuss.go-admin.com/c/Post-your-questions-or-problems-here-were-going-to-offer-help/E682A8E58FAFE4BBA5E59CA8E8AFA5E69DBFE59D97E4BDBFE794A8E4B8ADE69687E68F90E997AEE38081E68EA2E8AEA8E5928CE4BAA4E6B581E38082/9)
- [中文教程板块](http://discuss.go-admin.com/c/Share-your-examples-demos-and-guides-to-help-community-grow/%E6%82%A8%E5%8F%AF%E4%BB%A5%E5%9C%A8%E8%AF%A5%E6%9D%BF%E5%9D%97%E4%BD%BF%E7%94%A8%E4%B8%AD%E6%96%87%E5%8F%91%E5%B8%83%E6%95%99%E7%A8%8B%E3%80%81%E6%8E%A2%E8%AE%A8%E5%92%8C%E4%BA%A4%E6%B5%81%E3%80%82/10)
- [需求提案板块](http://discuss.go-admin.com/c/Any-proposals-about-GoAdmin-here/%E8%BF%99%E9%87%8C%E5%8F%AF%E4%BB%A5%E5%8F%91%E8%A1%A8%E4%BD%A0%E5%B8%8C%E6%9C%9B%E5%91%BC%E5%90%81GoAdmin%E5%A2%9E%E5%8A%A0%E7%9A%84%E9%9C%80%E6%B1%82%E5%B9%B6%E4%B8%8E%E5%A4%A7%E5%AE%B6%E8%AE%A8%E8%AE%BA/12)
- [Golang板块](http://discuss.go-admin.com/c/Discussions-about-technical-designs-and-implementations-of-Gogs/8)

**Comment by xjblszyy** [comment]
502手动狗头

**Comment by renews** [comment]
rip
