### ISSUE TITLE
[Question] 静态资源的 Content-Type 不正确

### ISSUE THREAD

**Issue by magichuihui** [GoAdminGroup/go-admin#215]
### 问题描述
按照文档的例子运行，为什么静态资源的 **Content-Type** 不正确
例如： 
.js => Content-Type: text/js; charset=utf-8
.ttf => Content-Type: image/ttf

### 其他信息 

``` bash
 curl -v http://127.0.0.1:9044/admin/assets/dist/css/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7g.ttf

* About to connect() to 127.0.0.1 port 9044 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9044 (#0)
> GET /admin/assets/dist/css/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7g.ttf HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9044
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: image/ttf
< Date: Tue, 07 Apr 2020 06:52:57 GMT
< Transfer-Encoding: chunked
< 
```

**Comment by chenhg5** [comment]
@magichuihui 我检查一下。

**Comment by magichuihui** [comment]
可以用Nginx模块[headers-more-nginx-module](https://github.com/openresty/headers-more-nginx-module)  重新设置 header， 但是还是想找到原因

**Comment by chenhg5** [comment]
@magichuihui  提交了一个修复 [#998268](https://github.com/GoAdminGroup/go-admin/commit/998268d25f7872b43ee631f7a3e522917575545e) 到master。

**Comment by magichuihui** [comment]
谢谢大佬，辛苦啦
