### ISSUE TITLE
[Proposal] 希望有个 SelectSingle 根据FieldOnChoose 选中的Options的ID，触发一个逻辑函数

### ISSUE THREAD

**Issue by cppfuns** [GoAdminGroup/go-admin#227]
[图片]
![image](https://user-images.githubusercontent.com/7980920/80325606-70e12100-8868-11ea-818d-234236cde37a.png)
这个值 ，如果是SelectSingle，是不是应该返回Options的ID？  也就是希望有个 SelectSingle 根据FieldOnChoose 选中的Options的ID，触发一个逻辑函数

**Comment by jingjie520** [comment]
可以参考一下：表单选择类型动态加载
http://doc.go-admin.cn/zh/admin/form/components/

`
// 自定义js，选中后触发该js内容
func (f *FormPanel) FieldOnChooseCustom(js template.HTML) *FormPanel

// 选中后触发内容，传入map，格式为：
// map[string]types.LinkField{
//      "men": {Field: "ip", Value:"127.0.0.1"},     
//      "women": {Field: "ip", Hide: true},
//      "other": {Field: "ip", Disable: true}
// }
// 意思是选中的值为men，则将ip这个表单项设置为127.0.0.1
// 选中的值为women，则将ip这个表单项设置为隐藏
// 选中的值为other，则将ip这个表单项设置为禁止输入
func (f *FormPanel) FieldOnChooseMap(m map[string]LinkField) *FormPanel

// 选中后触发，如果选中值为val，则将field这个表单项设置为value
func (f *FormPanel) FieldOnChoose(val, field string, value template.HTML) *FormPanel

// 选中后触发Ajax，选中后将选中的值通过ajax经url发到handler，返回的内容(data)将赋给field这个表单项，
// 如果返回的是字符串将直接赋值，如果返回的是对象则会赋为下拉表单的选项。对象格式为：
// [{"id":0, "text":"men"}, {"id":1, "text":"women"}]
func (f *FormPanel) FieldOnChooseAjax(field, url string, handler Handler) *FormPanel

// 选中后触发，如果选中值为val，则将对应field的表单项隐藏
func (f *FormPanel) FieldOnChooseHide(value string, field ...string) *FormPanel

// 选中后触发，如果选中值为val，则将对应field的表单项显示
func (f *FormPanel) FieldOnChooseShow(value string, field ...string) *FormPanel

// 选中后触发，如果选中值为val，则将对应field的表单项禁止
func (f *FormPanel) FieldOnChooseDisable(value string, field ...string) *FormPanel
`
