### ISSUE TITLE
[BUG] Firefox 中表单显示异常

### ISSUE THREAD

**Issue by weidongbcn** [GoAdminGroup/go-admin#229]
### bug 描述 [详细地描述 bug，让大家都能理解]
表单在 Firefox 浏览器中表现很不好，会缩成一团。在 opera, chrome 中表现基本正常。

### 版本信息:

- GoAdmin 版本：
- golang 版本：
- 浏览器环境：
- 开发环境：

**Comment by chenhg5** [comment]
@weidongbcn 最新版本已解决这个问题
