### ISSUE TITLE
[Question] Table model with a tuple like Primary Key

### ISSUE THREAD

**Issue by davidlcarrascal** [GoAdminGroup/go-admin#234]
### Description
I have a table where the Primary Key is: 
```sql
PRIMARY KEY (`user_id`,`partner_id`)
```
I have to config the table using this primary key. How could I do it?

### Example code
```go
adminPartnerTable := table.NewDefaultTable(
		table.Config{
			Driver:     os.Getenv("DB_DRIVER"),
			Connection: table.DefaultConnectionName,
			CanAdd:     true,
			Editable:   true,
			Deletable:  true,
			Exportable: false,
			PrimaryKey: table.PrimaryKey{
				Type: db.Int,
				Name: "(user_id, partner_id)",
			},
		})
```

**Comment by chenhg5** [comment]
@davidlcarrascal Sorry, it is still not supported yet. For now, you can query the data yourself using API ```SetGetDataFn```. Here is the [docs](https://book.go-admin.cn/en/admin-plugins/data-table/basic#writing-a-custom-data-source-function).
