### ISSUE TITLE
[Question]使用表单Ajax请求并显示结果弹窗

### ISSUE THREAD

**Issue by fantasysea** [GoAdminGroup/go-admin#236]
我有一个自定义的form需要提交数据，提交完成之后弹窗显示结果，但是我不知道怎么用这个框架实现。

**Comment by chenhg5** [comment]
@fantasysea 下一个版本可实现。提前体验：http://demo.go-admin.cn/admin/info/posts/new

调用方法很简单：

```go
// 参数一为成功显示信息，参数二为失败显示信息
formList.EnableAjax("成功", "失败")
```

**Comment by fantasysea** [comment]
> @fantasysea 下一个版本可实现。提前体验：http://demo.go-admin.cn/admin/info/posts/new
> 
> 调用方法很简单：
> 
> ```go
> // 参数一为成功显示信息，参数二为失败显示信息
> formList.EnableAjax("成功", "失败")
> ```

components.Form() 对象有这个方法吗？我不是在自动生成的page里面用 。

**Comment by chenhg5** [comment]
@fantasysea 有的。这两天会发新版本。也可以提前拉 master 下来体验。
