### ISSUE TITLE
[Question] build custom template

### ISSUE THREAD

**Issue by yogihardi** [GoAdminGroup/go-admin#237]
### Description 

Is there any documentation to create our own custom template instead using default `adminlte` template?

**Comment by chenhg5** [comment]
@yogihardi There is no documentation to build a new custom template for detail now. You can see the default ```adminlte``` template code for reference.

https://github.com/GoAdminGroup/themes/blob/master/adminlte/adminlte.go
https://github.com/GoAdminGroup/themes/blob/master/adminlte/Makefile
