### ISSUE TITLE
[BUG] Field is always false with the Postgresql driver

### ISSUE THREAD

**Issue by davidlcarrascal** [GoAdminGroup/go-admin#240]
### Bug Description [describe the bug in detail]
I have a table with a **boolean** field in a heroku postgres database (v12.2). 
When a info field is added with db.Boolean or similar type with goadmin, the field always prints false. I have checked with: 

```go
info.AddField("Paused 0", "paused", db.Boolean)
info.AddField("Paused 1", "paused", db.Bool)
info.AddField("Paused 2", "paused", db.Int)
info.AddField("Paused 3", "paused", db.Tinyint)
```

**Comment by chenhg5** [comment]
@davidlcarrascal  Made a fix. [5dc13b](https://github.com/GoAdminGroup/go-admin/commit/5dc13b8ae5b8739ec0f808c6a9978387c8f73904)

**Comment by davidlcarrascal** [comment]
@chenhg5 Thanks!! Do I have to use the latest version?
