### ISSUE TITLE
[BUG] GoAdmin CLI generate table model files error

### ISSUE THREAD

**Issue by andraantariksa** [GoAdminGroup/go-admin#242]
### Bug Description

adm somewhat error to generate the tables

```
  92% |████████████████████████████████████    | [0s:0s]            
GoAdmin CLI error: 14:7: expected 'IDENT', found ':=' (and 4 more errors)
```

### How to reproduction

Create an empty folder
Run `adm`

```
? choose a driver mysql
? sql address 127.0.0.1
? sql port 3306
? sql username wspeople_devel
? sql password **************
? sql database name clearance2
? choose table to generate  [Use arrows to move, space to select, type to filt? choose table to generate  [Use arrows to move, space to select, type to filt? choose table to generate [select all]
? set package name main
? set connection name default
? set file output path ./
? generate permission records for tables, Y on behalf of yes N

✔ generating: 

  92% |████████████████████████████████████    | [0s:0s]            
GoAdmin CLI error: 14:7: expected 'IDENT', found ':=' (and 4 more errors)
```

### Expect

GoAdmin CLI can generate the code for all table

### Versions

- GoAdmin version: `GoAdmin CLI v1.2.11`
- golang version: `go version go1.14.2 linux/amd64`
- OS [e.g. mac OS]: Manjaro Linux 20

**Comment by chenhg5** [comment]
@andraantariksa I can not reproduce the error. Are there any files generated? Could you show me any clues about the content of the generated files or your database table structure?

**Comment by andraantariksa** [comment]
This is the database that I use

https://1drv.ms/u/s!AmWkLtcHHHJ4hV8WXlO_aHGtKBjr?e=nrTCue

**Comment by chenhg5** [comment]
@andraantariksa Thanks. I made a fix to the master branch. [40d8f5](https://github.com/GoAdminGroup/go-admin/commit/40d8f531e77b3aaedfd9e6dcb9d5c6ce69ada2db)

**Comment by andraantariksa** [comment]
Thank you, I will try it
