### ISSUE TITLE
[Question]关于pageSize类型的问题

### ISSUE THREAD

**Issue by maliyan** [GoAdminGroup/go-admin#244]
### 问题描述
`Error 1064: Proxy ERROR:You have an error in your SQL syntax; check the manual that corresponds to your Mysql server version for the right syntax to use near ''10' OFFSET 0' at line 1`

不确定是不是腾讯云的TDSQL的问题，跟了下代码，在`plugins/admin/modules/table/default.go:471`发现了`params.PageSize`是string类型的，这样会导致执行的sql报错，手动改成int就可以了

不确定是不是GoAdmin的问题，还是腾讯云TDSQL的某些设置的问题

**Comment by chenhg5** [comment]
@maliyan 我看下
