### ISSUE TITLE
[Question]关于count(1)、count(*)的问题

### ISSUE THREAD

**Issue by maliyan** [GoAdminGroup/go-admin#245]
### 问题描述 
`plugins/admin/modules/table/default.go:526`
这里会报错`interface conversion: interface {} is nil, not int64`，输出了下`total[0]`，发现key是`count(1)`，而不是`count(*)`

不确定什么时候会用到count(*)、什么时候会用到count(1)

**Comment by maliyan** [comment]
加了这个判断临时解决了，但是，没有细看具体的原因

![image](https://user-images.githubusercontent.com/5624855/82856266-19ee6a80-9f40-11ea-8550-492d4c8aae67.png)

**Comment by chenhg5** [comment]
@maliyan 怎么重现这个问题？有重现步骤吗？

**Comment by maliyan** [comment]
> @maliyan 怎么重现这个问题？有重现步骤吗？

嗯嗯，晚些我跟下代码，看看怎么重现

**Comment by maliyan** [comment]
跟了下代码，不确定是不是数据集数量太大的原因（100w条）

涉及的文件：github.com/GoAdminGroup/go-admin/plugins/admin/modules/table/default.go:524
传入的参数：
- countCmd：select count(*) from `tbl_vid_playcnt`  
- whereArgs: []

`total, err := connection.QueryWithConnection(tb.connection, countCmd, whereArgs...)`
total返回值：
[map[count(1):1033493]]

怀疑出问题的地方：
涉及的文件：github.com/GoAdminGroup/go-admin/modules/db/performer.go:57
问题的现象：`count(*)`变成了`count(1)`
debug信息：SetResultValue: j: 0, col: [count(1)], colVar: [0xc000269820], typeName: BIGINT

**Comment by maliyan** [comment]
好像是腾讯云的问题，同样的代码在执行`db.Query("select count(*)")`会变成`db.Query("select count(1)")`
