### ISSUE TITLE
[BUG]多数据库,非default数据库,无法在生成表单模型里进行连接

### ISSUE THREAD

**Issue by zjlx** [GoAdminGroup/go-admin#247]
### bug 描述 [详细地描述 bug，让大家都能理解]
多数据库,非default数据库,无法在生成表单模型里进行连接
### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
在main.go里Databases: config.DatabaseList增加第二个数据库配置后,在生成表单模型工具里,选择这个数据库网页弹出提示error,控制台显示?[31mERROR?[0m  logger/logger.go:316    interface conversion: interface {} is nil, not string

### 版本信息:

- GoAdmin 版本：v1.2.11
- golang 版本：1.14.2
- 浏览器环境：chrome81
- 开发环境：Windows64

**Comment by chenhg5** [comment]
@zjlx 有更详细错误信息吗？确认一下，1. 数据库配置有没问题，2. 是否有将数据模型加到 Generators

**Comment by zjlx** [comment]
抱歉,为生成数据模型的原因
