### ISSUE TITLE
[Question]是不是admin账户不受NoLimitLoginIP限制呢？

### ISSUE THREAD

**Issue by maliyan** [GoAdminGroup/go-admin#249]
### Description [describe your questions]
已经在配置中将NoLimitLoginIP置为true，但是，发现admin账户登录后，会把“另外”一个admin踢掉

**Comment by chenhg5** [comment]
@maliyan 当前版本配置是以数据库为准，启动后在网站右上角进入网站设置页面中设置才能生效。

**Comment by maliyan** [comment]
> @maliyan 当前版本配置是以数据库为准，启动后在网站右上角进入网站设置页面中设置才能生效。
> 
> ![](https://camo.githubusercontent.com/4ecc9301c46c4d8324048803110e32d8f1f2e0cb/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303753385a496c677931676630336133666c62686a33307771303461676c782e6a7067)

好的，多谢~~
