### ISSUE TITLE
How to solve this issue(a kind of bug)?

### ISSUE THREAD

**Issue by HongJaison** [GoAdminGroup/go-admin#250]
### Description
I am a fan of GoAdmin.
But can you check this issue and help me to solve it?
I cloned the latest git repository and this occurred.
it was working well with the code I cloned about 1 week ago.

### Example code
...
...
go: finding github.com/satori/go.uuid v1.2.0
go: finding github.com/360EntSecGroup-Skylar/excelize v1.4.1
go: finding github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: finding golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
go: finding github.com/go-sql-driver/mysql v1.5.0
go: finding github.com/gobuffalo/packd v1.0.0
go: finding github.com/gobuffalo/logger v1.0.3
go: finding github.com/sirupsen/logrus v1.4.2
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.2
go: finding github.com/karrick/godirwalk v1.15.3
go: finding github.com/markbates/errx v1.1.0
go: finding github.com/markbates/oncer v1.0.0
go: finding github.com/markbates/safe v1.0.1
# github.com/GoAdminGroup/themes/adminlte
..\..\..\..\..\..\pkg\mod\github.com\!go!admin!group\themes@v0.0.33\adminlte\adminlte.go:48:32: cannot use &Adminlte (type *Theme) as type "github.com/GoAdminGroup/go-admin/template".Template in argument to "github.com/GoAdminGroup/go-admin/template".Add:
        *Theme does not implement "github.com/GoAdminGroup/go-admin/template".Template (wrong type for GetTemplate method)
                have GetTemplate(bool) (*"html/template".Template, string)
                want GetTemplate(bool, ..."github.com/GoAdminGroup/go-admin/template".PageType) (*"html/template".Template, string)

### screenshot
![image](https://user-images.githubusercontent.com/22753494/82539369-ec8c7000-9b7f-11ea-9ffb-17d1ef411a57.png)

**Comment by chenhg5** [comment]
@HongJaison Follow this [example](https://github.com/GoAdminGroup/example) step by step.

**Comment by HongJaison** [comment]
but can't I use the latest commit?

**Comment by HongJaison** [comment]
The example worked fine, but I just wanted to experience plugins from the latest GoAdmin
