### ISSUE TITLE
[Question] Migrate database to update the new version

### ISSUE THREAD

**Issue by davidlcarrascal** [GoAdminGroup/go-admin#251]
### Description [describe your questions]
I want to update to the latest version of go-admin but I have to update the database with the migration data. I am running this sql file but it returns me the error below. 
My database is Postgres and the file is: https://github.com/GoAdminGroup/go-admin/blob/master/data/migrations/admin_2020_04_14_100427_postgres.sql
Is there any other way to do it?

### Example code [If you have any code info]
```
ERROR:  relation "public.goadmin_site_myid_seq" does not exist
LINE 2:     id integer DEFAULT nextval('public.goadmin_site_myid_seq...
                                       ^
ERROR:  relation "public.goadmin_site" does not exist
ERROR:  relation "public.goadmin_site" does not exist
invalid command \N
invalid command \.
ERROR:  syntax error at or near "2"
LINE 1: 2 theme adminlte 0 
```

**Comment by chenhg5** [comment]
@davidlcarrascal You can try again now. I updated the SQL. https://github.com/GoAdminGroup/go-admin/blob/master/data/migrations/admin_2020_04_14_100427_postgres.sql

**Comment by davidlcarrascal** [comment]
Thanks!!

**Comment by mustaqeem** [comment]
@davidlcarrascal how did you migrated? Did we need to drop database and recreate DB and load the postgres dump?
If we do so, the audit data will be flushed.

**Comment by davidlcarrascal** [comment]
@mustaqeem No, I just ran the new fixed sql.

**Comment by mustaqeem** [comment]
@davidlcarrascal then audit records will be flushed? right?
