### ISSUE TITLE
[Question] Replace the default Delete logic

### ISSUE THREAD

**Issue by davidlcarrascal** [GoAdminGroup/go-admin#254]
### Description [describe your questions]
Is it possible to replace the default Delete logic with a function? Just like insert (SetInsertFn) or update (SetUpdateFn).

**Comment by chenhg5** [comment]
@davidlcarrascal use API, [info.SetDeleteFn()](https://godoc.org/github.com/GoAdminGroup/go-admin/template/types#InfoPanel.SetDeleteFn)

**Comment by davidlcarrascal** [comment]
@chenhg5 Thanks!!
