### ISSUE TITLE
[BUG]form.Multifile无法编辑

### ISSUE THREAD

**Issue by jianzhiyao** [GoAdminGroup/go-admin#257]
### bug 描述 [详细地描述 bug，让大家都能理解]
上传多文件后无法正常编辑

### 期望结果 [描述你原本期望看到的结果]
上传多文件后正常编辑
### 复现代码 [提供可复现的代码，仓库，或线上示例]
```go
formList.AddField("Images", "images", db.Varchar, form.Multifile).FieldOptionExt(map[string]interface{}{
		"maxFileCount": 3,
	})
```
### 版本信息:

- GoAdmin 版本：github.com/GoAdminGroup/go-admin v1.2.13
- golang 版本：go version go1.14.2 windows/amd64
- 浏览器环境：chrome
- 开发环境：windows

**Comment by chenhg5** [comment]
@jianzhiyao 提交了一个修复，[e5e7e4ef](https://github.com/GoAdminGroup/go-admin/commit/e5e7e4ef909f626513d25ff2279db525f6b03be7)。

当前版本可以这样写：

```
formList.AddField("Images", "images", db.Varchar, form.Multifile).FieldOptionExt(map[string]interface{}{
		"maxFileCount": 3,
	}).FieldDisplay(func(value types.FieldModel) interface{} {
			if value.Value == "" {
				return ""
			}
			arr := strings.Split(value.Value, ",")
			res := "["
			for i, item := range arr {
				if i == len(arr)-1 {
					res += "'" + config.GetStore().URL(item) + "']"
				} else {
					res += "'" + config.GetStore().URL(item) + "',"
				}
			}
			return res
		})

```

**Comment by jianzhiyao** [comment]
> @jianzhiyao 提交了一个修复，[e5e7e4ef](https://github.com/GoAdminGroup/go-admin/commit/e5e7e4ef909f626513d25ff2279db525f6b03be7)。
> 
> 当前版本可以这样写：
> 
> ```
> formList.AddField("Images", "images", db.Varchar, form.Multifile).FieldOptionExt(map[string]interface{}{
> 		"maxFileCount": 3,
> 	}).FieldDisplay(func(value types.FieldModel) interface{} {
> 			if value.Value == "" {
> 				return ""
> 			}
> 			arr := strings.Split(value.Value, ",")
> 			res := "["
> 			for i, item := range arr {
> 				if i == len(arr)-1 {
> 					res += "'" + config.GetStore().URL(item) + "']"
> 				} else {
> 					res += "'" + config.GetStore().URL(item) + "',"
> 				}
> 			}
> 			return res
> 		})
> ```

依然不行，能显示了，再点击保存数据没了

**Comment by hoseadevops** [comment]
如何解决

**Comment by junyongNie** [comment]
我也遇到了这个问题

**Comment by junyongNie** [comment]
> > @jianzhiyao 提交了一个修复，[e5e7e4ef](https://github.com/GoAdminGroup/go-admin/commit/e5e7e4ef909f626513d25ff2279db525f6b03be7)。
> > 当前版本可以这样写：
> > ```
> > formList.AddField("Images", "images", db.Varchar, form.Multifile).FieldOptionExt(map[string]interface{}{
> > 		"maxFileCount": 3,
> > 	}).FieldDisplay(func(value types.FieldModel) interface{} {
> > 			if value.Value == "" {
> > 				return ""
> > 			}
> > 			arr := strings.Split(value.Value, ",")
> > 			res := "["
> > 			for i, item := range arr {
> > 				if i == len(arr)-1 {
> > 					res += "'" + config.GetStore().URL(item) + "']"
> > 				} else {
> > 					res += "'" + config.GetStore().URL(item) + "',"
> > 				}
> > 			}
> > 			return res
> > 		})
> > ```
> 
> 依然不行，能显示了，再点击保存数据没了

GoAdminGroup/go-admin 表单 form.Multifile 编辑时候保存，内容被清空问题 https://psd1403.com/article?n=43

**Comment by foundVanting** [comment]
+1
