### ISSUE TITLE
[BUG] yml配置文件无法读取

### ISSUE THREAD

**Issue by ghost-void** [GoAdminGroup/go-admin#259]
### bug 描述

yml配置文件无法读取

### 复现步骤

eng.AddConfigFromYAML("config.yml")

直接说原因吧，Config定义里面 `json:"database,omitempty",yaml:"database",ini:"database"`

 `json:"database,omitempty" yaml:"database" ini:"database"`

这些tag应该用空格隔开这里，是逗号，yaml无法正确解析

**Comment by chenhg5** [comment]
@ghost-void 提交了一个修复。[2109ee](https://github.com/GoAdminGroup/go-admin/commit/2109ee3bb4a341f7298e82fd49d89fdac78557eb)
