### ISSUE TITLE
[Question] 配置domain 修改为域名无效

### ISSUE THREAD

**Issue by smirkcat** [GoAdminGroup/go-admin#260]
### 问题描述 [详细地描述问题，让大家都能理解]
原来配置为ip 现设置为域名 本地host映射 当进入登录页登录时 不断提示登录ip限制
### 其他信息 [如截图等其他信息可以贴在这里]
go-admin 1.2.13

**Comment by chenhg5** [comment]
@smirkcat 新版本中可以测试下。先关闭此issue，如有问题可再打开。

**Comment by tozh** [comment]
同样的问题，设置domain并不管用
