### ISSUE TITLE
[Question] How to generate table with custom type?

### ISSUE THREAD

**Issue by msmaromi** [GoAdminGroup/go-admin#266]
### Description [describe your questions]
Let's say I Have `Order` table with `status` property with `status_type`. The `status_type` is enum ("success", "waiting"). I know how to configure this custom `status_type` in gin framework. But when I generate in GoAdmin `status` property just becom a text. Is there any way to auto generate the custom type or in GoAdmin FieldOptions?

**Comment by ingted** [comment]
Workaround:

![image](https://user-images.githubusercontent.com/4289161/85196236-617fd080-b30b-11ea-84e9-081d2f0a92bf.png)

add type to type.go

![image](https://user-images.githubusercontent.com/4289161/85196219-43b26b80-b30b-11ea-834f-95ae1d2521b8.png)

and add byte array to string(or another type) code snippet in GetValueFromSQLOfDatabaseType:

![image](https://user-images.githubusercontent.com/4289161/85196256-8d02bb00-b30b-11ea-8577-d0308332cb71.png)

**Comment by msmaromi** [comment]
I see, so it means we need to custom the go-admin source code. Thanks for the hint @ingted.
