### ISSUE TITLE
[Proposal]批量更新数据应该怎样实现

### ISSUE THREAD

**Issue by xiaogu-space** [GoAdminGroup/go-admin#274]
### 需求描述 [详细地描述需求，让大家都能理解]
现在需要批量更新，添加数据应该怎样弄

**Comment by Johnhawk-luo** [comment]
上传文件，在后台解析文件内容，然后更新数据库

**Comment by xiaogu-space** [comment]
> 上传文件，在后台解析文件内容，然后更新数据库

就是在代码中怎样批量插入数据库没找到实现

**Comment by Johnhawk-luo** [comment]
取到数据库连接，自己写insert语句插入数据库啊
