### ISSUE TITLE
[BUG] CustomContent中模板语法没有被解析

### ISSUE THREAD

**Issue by hb1707** [GoAdminGroup/go-admin#276]
### bug 描述

官网文档说在CustomContent，CustomCss，CustomJs中会传入一个FormField类型进行模板渲染。

可以在CustomContent中，使用这样的模板语法来表示编辑时字段的值：{{.Value}}

但实际并没有解析{{.Value}}

FieldCustomJs 亦有此问题

### 复现步骤

官网介绍：
![TIM图片20200621112233](https://user-images.githubusercontent.com/19995502/85215940-947c9f80-b3b1-11ea-98ab-232dacb3a477.png)

代码写法：
![微信截图_20200621112703](https://user-images.githubusercontent.com/19995502/85215998-2d131f80-b3b2-11ea-9b9f-9a585abfa4d3.png)

前端显示：
![TIM图片20200621112245](https://user-images.githubusercontent.com/19995502/85215939-947c9f80-b3b1-11ea-8cd7-58b6f89e4fc5.png)

### 期望结果

前端不应该直接显示{{.Value}}这个未解析的字符串

### 复现代码

`panel.AddField("xxx", "xxx", db.Varchar, form.Custom).FieldCustomContent("{{.Value}}")`

### 版本信息:

- GoAdmin 版本：1.2.13
- golang 版本：1.14
- 浏览器环境：Google Chrome
版本 83.0.4103.106（正式版本） （64 位）
- 开发环境：goland

**Comment by chenhg5** [comment]
@hb1707 试一下，GoAdmin升级到 1.2.14，Themes升级到 0.0.37

**Comment by hb1707** [comment]
我今天升级到最新1.2.14版，这个版本的模板错误会被捕获并打印出来，这个改进帮助我排查到了最终原因。

抱歉，经过排查发现确实还是我自己的问题：
我是把 f := types.NewFormPanel()单独提取出来，生成的表单。
f.AddField之后，发现是必须要在后面带上 f.FieldsWithDefaultValue()，模板代码就能被解析了。

不过也因新版本对错误日志的打印，发现另外一个值得改进的地方：github.com\GoAdminGroup\go-admin\template\types\form.go
第302行，可以考虑在 t := template.New("custom")后面加上.Funcs(adminTemplate.DefaultFuncMap)
如此一来Custom部分应该可以复用到你们的func。
