### ISSUE TITLE
[Question] 在数据表单页面希望添加关联的其他表中的数据，如何进行页面跳转？

### ISSUE THREAD

**Issue by shuiboshi** [GoAdminGroup/go-admin#281]
没有找到相应的方法能够从表单编辑页面跳转到其他表单编辑页面的方法。

例如，我在添加商品的时候，需要给商品选择一个分类，在当前所有分类都不满足的情况下，需要跳转到分类表单去添加一个分类，这个时候我尝试自定义html进行跳转，如下：
```
formList.AddField("新增类目", "custom", db.Varchar, form.Custom).
		FieldCustomContent(template.HTML(`<button class='add_button' click="addCategory">添加类目</button>`)).
		FieldCustomCss(template.CSS(`.add_button {background-color: #f5f6f8;}`)).
		FieldCustomJs(template.JS(`function addCategory(){window.location.href="www.baidu.com"}`))

```
但是，上面的按钮在点击的时候，默认是保存事件。目前也没有找到相关的例子可以进行参考。

**Comment by chenhg5** [comment]
@shuiboshi 管理员页面就是一个例子，其代码在这里：https://github.com/GoAdminGroup/go-admin/blob/master/plugins/admin/modules/table/generators.go#L153
