### ISSUE TITLE
[Proposal]

### ISSUE THREAD

**Issue by shuiboshi** [GoAdminGroup/go-admin#285]
### 需求描述 

两张表关联，如店铺表关联用户表（店主），在店铺表中希望点击店主跳转到用户表，或者查看店主信息

### 解决方案 

为字段添加action动作，点击可以pop或者jump

**Comment by chenhg5** [comment]
@shuiboshi [demo](http://demo.go-admin.cn/admin)中有类似功能，可以参考一下。pop或jump都有。
