### ISSUE TITLE
[BUG] form.Number 类型的form组件FieldNotAllowEdit()不生效

### ISSUE THREAD

**Issue by zeusYi** [GoAdminGroup/go-admin#286]
代码:
	formList.AddField("年龄", "age", db.Int, form.Number).FieldInputWidth(5).FieldNotAllowEdit()

我想禁用edit 年龄的功能，但是无效

![record](https://user-images.githubusercontent.com/22519964/87146912-4555ca80-c2de-11ea-8856-a48e5c8e9a68.gif)

**Comment by zeusYi** [comment]
不管不问

**Comment by chenhg5** [comment]
@zeusYi 不好意思，遗漏了。最近在忙调整插件这块。接下来会逐步修复这些问题。

**Comment by chenhg5** [comment]
@zeusYi 提交了一个修复 [#18e4e8](https://github.com/GoAdminGroup/themes/commit/2d7c321d4e886ee810339c475f0f3c5a9618e4e8)
