### ISSUE TITLE
[BUG] 详情页底部没有加入detail.FooterHtml相关代码

### ISSUE THREAD

**Issue by hb1707** [GoAdminGroup/go-admin#287]
### bug 描述 [详细地描述 bug，让大家都能理解]

详情页底部没有加入detail.FooterHtml相关代码

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

见下文复现代码

### 期望结果 [描述你原本期望看到的结果]

详情页底部FooterHtml可以自定义

### 复现代码 [提供可复现的代码，仓库，或线上示例]

见官网demo页
https://demo.go-admin.cn/admin/info/user/detail?__page=1&__pageSize=10&__sort=id&__sort_type=desc&__goadmin_detail_pk=3632

![微信截图_20200712151538](https://user-images.githubusercontent.com/19995502/87241131-97b7f800-c452-11ea-80af-385d083d6c72.png)

点击截图里面的按钮没反应

### 版本信息:

- GoAdmin 版本：v1.2.14，theme：v0.0.37
- golang 版本：1.14
- 浏览器环境：chrome
- 开发环境：goland

### 其他信息 [如截图等其他信息可以贴在这里]
建议修复方案：
```
github.com\GoAdminGroup\go-admin\plugins\admin\controller\detail.go  149行
`SetFooter(template.HTML(deleteJs)).`
改成
`SetFooter(detail.FooterHtml+template.HTML(deleteJs)).`
```

**Comment by chenhg5** [comment]
@hb1707 提交了一个修复。[#1ad78d](https://github.com/GoAdminGroup/go-admin/commit/1ad78db3eed3ab7591d9548cd2fd1afe180e7537)
