### ISSUE TITLE
[BUG] echo + go-admin，修改网站配置或登出，跳转页面无内容显示

### ISSUE THREAD

**Issue by imxxiv** [GoAdminGroup/go-admin#288]
### bug 描述 [详细地描述 bug，让大家都能理解]
echo + go-admin + sqlite，修改网站配置后，跳转页面无内容显示，登出后也无内容显示

sqlite文件来源：https://gitee.com/go-admin/go-admin/raw/master/data/admin.db，
管理菜单下面的子菜单使用正常，可以浏览，修改用户，新建用户。

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
bug1：登录后台后，修改网站设置中的配置（例如切换Debug模式），点击保存，弹窗显示完成后，浏览器会跳到/admin/info/site?__page=1&__pageSize=10&__sort=id&__sort_type=desc，页面无内容显示

bug2：点击 登出 按钮后，跳到 /admin/logout，页面无内容显示

### 期望结果 [描述你原本期望看到的结果]
用 gin+go-admin + sqlite 和 fasthttp + go-admin + sqlite 测试，修改网站设置项目和登出，都可以正常显示下个页面。

### 复现代码 [提供可复现的代码，仓库，或线上示例]

```
package main

import (
	_ "github.com/GoAdminGroup/go-admin/adapter/echo"
	_ "github.com/GoAdminGroup/go-admin/modules/db/drivers/sqlite"
	_ "github.com/GoAdminGroup/themes/adminlte"

	"github.com/GoAdminGroup/go-admin/engine"
	"github.com/GoAdminGroup/go-admin/modules/config"
	"github.com/GoAdminGroup/go-admin/modules/language"
	"github.com/labstack/echo/v4"
)

func main() {
	e := echo.New()

	eng := engine.Default()

	cfg := config.Config{
		Databases: config.DatabaseList{
			"default": {
				File:   "./admin" + ".db",
				Driver: config.DriverSqlite,
			},
		},
		UrlPrefix: "admin",
		IndexUrl:  "/info/manager",
		Store: config.Store{
			Path:   "./uploads",
			Prefix: "uploads",
		},
		Language: language.CN,
	}

	if err := eng.AddConfig(cfg).
		Use(e); err != nil {
		panic(err)
	}

	e.Static("/uploads", "./uploads")

	// Start server
	go e.Logger.Fatal(e.Start(":21323"))
}
```

### 版本信息:

- GoAdmin 版本：1.2.14
- golang 版本：1.14.4
- 浏览器环境：firefox / cent browser (Chromium 80.0.3987.163)
- 开发环境：debian / windows 10

**Comment by chenhg5** [comment]
@imxxiv 重现不出来你的问题。能否提供一下视频或截图资料？

**Comment by imxxiv** [comment]
![登出后的截图](https://user-images.githubusercontent.com/26142642/89154815-37702e00-d59a-11ea-9e5c-786b941590b8.png)

![修改网站配置后返回的页面](https://user-images.githubusercontent.com/26142642/89155129-d2690800-d59a-11ea-8d11-71f2d393a92a.png)

**Comment by chenhg5** [comment]
@imxxiv 提交了一个修复：[#228e70](https://github.com/GoAdminGroup/go-admin/commit/228e70d472001bc6c6a5e965cd631fb712972ab2)
