### ISSUE TITLE
升级后发现无法获取另一个表单数据[Question]

### ISSUE THREAD

**Issue by JackySmith** [GoAdminGroup/go-admin#290]
### 问题描述 [详细地描述问题，让大家都能理解]

前几个月部署了一个后台，当时在一个表单中使用如下代码获取另一个表数据没问题
![image](https://user-images.githubusercontent.com/7380379/88452115-a2c94a00-ce8e-11ea-884d-67f3817595f4.png)

前两天升级后，发现GetDataFromDatabase这个函数用不了了
新的版本只有GetData比较相似，使用这个函数，但代入参数 parameter.GetParam(nil, 10, "id", "asc") 后一直报错
导致无法获取得到另一个表的查询数据。请教是函数用错了吗，或者说新函数的正确使用方法应该是怎么样的。谢谢

**Comment by chenhg5** [comment]
@JackySmith 当前通过数据库模块获取数据的方法可以参考文档：http://doc.go-admin.cn/zh/admin/module/#_2
