### ISSUE TITLE
[Question]使用表单组件时，怎么读取数据库里的数据

### ISSUE THREAD

**Issue by megustas2xj** [GoAdminGroup/go-admin#291]
### 问题描述 [详细地描述问题，让大家都能理解]
不用表格，用表单页面时 怎么读数据库中的数据
### 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/37738743/88473723-ef765900-cf52-11ea-9213-fe0eb25deb60.png)

**Comment by chenhg5** [comment]
@megustas2xj http://doc.go-admin.cn/zh/admin/module/#_2

**Comment by megustas2xj** [comment]
@chenhg5 哥，还是不太明白，就是能不能像table一样 类似info.AddField获取数据，有类似的demo吗，谢谢谢谢！

**Comment by megustas2xj** [comment]
@chenhg5 这个自定义页面怎么跟数据库表关联起来呢？SetTable好像无效

**Comment by chenhg5** [comment]
@megustas2xj http://discuss.go-admin.com/t/goadmin-golang/17 参照这个教程走一遍
