### ISSUE TITLE
[BUG] form.RichText 字段问题

### ISSUE THREAD

**Issue by panaoshuai** [GoAdminGroup/go-admin#296]
在使用form.RichText时，同样的数据不做修改，重复提交但是代码中的html标签会被过滤掉，没有触发，会消失
目前官方demo也有这个问题
请告知一下有什么方案可以解决这个问题吗

**Comment by chenhg5** [comment]
@panaoshuai 有使用```AddXssJsFilter```类似api吗，试下去掉看看。

**Comment by panaoshuai** [comment]
@chenhg5 你好我已经测试过了，其他的api也测试了一遍，还是无法解决这个问题，同一个数据只是重复提交html标签就消失了，
formList.AddField("文章内容", "content", db.Text, form.RichText) 是这样使用的，没有使用其他的插件和相关api

**Comment by chenhg5** [comment]
@panaoshuai 不能重现，方便提供一下你设置的html标签内容吗？或者提供下相关截图。

**Comment by panaoshuai** [comment]
@chenhg5 下面是我进行的流程
![$B@4YJH0{E$SBZ H 46PLDR](https://user-images.githubusercontent.com/16750820/89151818-6388b080-d594-11ea-8f26-252ff0c441d3.png)
数据列表
![M BUQS04V)Y@@S2@LV}K@0](https://user-images.githubusercontent.com/16750820/89151837-6be0eb80-d594-11ea-9e43-47103d1f068f.png)
初始内容
![J)E6ME8BIF2 BVZBF`LWUI0](https://user-images.githubusercontent.com/16750820/89151852-713e3600-d594-11ea-929b-4611ec691200.png)
修改之后
![G6W(`F6 {VS~8$PP1MIWM6M](https://user-images.githubusercontent.com/16750820/89151860-7602ea00-d594-11ea-8006-e37d8341464d.png)
修改完数据保存之后查看
![~ QCGML@27 {$ 3NXG0A1Q0](https://user-images.githubusercontent.com/16750820/89151869-7a2f0780-d594-11ea-8a1d-03e3e6113cd8.png)
然后只保存，不进行数据修改

package tables

import (
	"github.com/GoAdminGroup/go-admin/context"
	"github.com/GoAdminGroup/go-admin/modules/db"
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
	"github.com/GoAdminGroup/go-admin/template/types"
	"github.com/GoAdminGroup/go-admin/template/types/form"
)

func GetFArticleTable(ctx *context.Context) table.Table  {

	fArticle := table.NewDefaultTable(table.DefaultConfigWithDriver("mysql"))

	info := fArticle.GetInfo().HideFilterArea()

	info.AddField("文章id", "id", db.Int).FieldFilterable()
	info.AddField("文章标题", "title", db.Varchar)
	info.AddField("类型", "type", db.Varchar)
	info.AddField("状态", "state", db.Tinyint)
	info.AddField("显示时间", "show_time", db.Datetime)
	info.HideExportButton()
	info.SetTable("f_article").SetTitle("文章").SetDescription("文章列表")

	formList := fArticle.GetForm()
	formList.AddField("文章标题", "title", db.Varchar, form.Text)
	formList.AddField("文章内容", "content", db.Text, form.RichText)
	formList.AddField("一句话简介", "desc", db.Varchar, form.Text).FieldHelpMsg("请不要超过30个字")
	formList.AddField("展示图片", "img", db.Varchar, form.Text).FieldHelpMsg("输入图片地址，上传图片请点击上传按钮获取图片地址")
	formList.AddField("添加标签", "type", db.Tinyint, form.Select).
		FieldOptions(types.FieldOptions{
		{Text:"beer",Value:"1"},
		{Text:"juice",Value:"2"},
	})
	formList.AddField("是否发布", "state", db.Tinyint, form.Radio).
		FieldOptions(types.FieldOptions{
			{Text: "是",Value: "1"},
			{Text: "否",Value: "2"},
		}).
		FieldDisplay(func(model types.FieldModel) interface{} {
		return  []string{"1"}
	})
	formList.AddField("显示时间", "show_time", db.Varchar, form.Datetime)
	formList.HideContinueEditCheckBox()
	formList.HideContinueNewCheckBox()

	formList.SetTable("f_article").SetTitle("文章").SetDescription("添加/编辑文章")

	return fArticle

}
这个是我使用的代码内容
麻烦您解答一下辛苦了，我是使用的adm init 创建的beego项目使用了，万分感谢

**Comment by chenhg5** [comment]
@panaoshuai 你的意思是输入内容的换行没了是吗？你设置的开发环境是不是生产环境？

**Comment by panaoshuai** [comment]
@chenhg5 不只是换行，其他的标签也会消失，尝试过插入代码，图片，视频，开发环境我是使用的测试环境

**Comment by chenhg5** [comment]
@panaoshuai 重现不出来你的问题。你试一下在线上demo能不能重现：http://demo.go-admin.cn/admin/info/posts/edit。然后再描述仔细一些你的重现步骤，比如什么时候按的保存，用的浏览器是什么等。

**Comment by panaoshuai** [comment]
我是使用的chrome浏览
复现步骤：
1.随便选取一条数据修改里面的内容，添加一些携带html标签的内容
2.点击保存（这时候保存完毕之后数据里面的html的标签是存在的）
3.再次编辑同一条数据不对内容进行修改直接保存内容会消失
注：有时标签内容不会消失，但是只要重发步骤3，只保存数据但是标签还是会消失，目前不清楚具体什么原因导致的
https://demo.go-admin.cn/admin/info/posts/edit?__page=1&__pageSize=10&__sort=id&__sort_type=desc&__goadmin_edit_pk=97 这是我测试使用的数据，目前内容无标签内容

**Comment by chenhg5** [comment]
@panaoshuai 提交了一个修复：[#39d95b](https://github.com/GoAdminGroup/themes/commit/39d95bb05acad2aa90f65e6d0d59ea5e3890350d)

**Comment by panaoshuai** [comment]
谢谢大佬的修复，万分感谢 @chenhg5

**Comment by fwan922** [comment]
为什么我更新到最新版本还是有这个问题
![image](https://user-images.githubusercontent.com/41473521/91690125-02a2c700-eb98-11ea-823d-9664b79abcd7.png)
