### ISSUE TITLE
Unable to setup goadmin

### ISSUE THREAD

**Issue by krishnathokala** [GoAdminGroup/go-admin#316]
### Description : Unable to setup the goadmin. Could any one provide me the steps to setup goadmin. 
When i am trying to run go install github.com/GoAdminGroup/go-admin/adm command i am getting below error.
cannot find package "github.com/GoAdminGroup/go-admin/adm" in any of: c:\go\src\github.com\GoAdminGroup\go-admin\adm (from $GOROOT) C:\Users\krish\go\src\github.com\GoAdminGroup\go-admin\adm (from $GOPATH)
Can anyone help me in setting up the application. Attached the screenshot below. Also when i try to import the postgressql provided we are getting errors in the copy command .
![gopackageerror](https://user-images.githubusercontent.com/4537278/90639507-63530b00-e24c-11ea-96aa-a36f5f846274.PNG)

**Comment by chenhg5** [comment]
@krishnathokala Try to download it directly here, https://github.com/GoAdminGroup/go-admin/releases
