### ISSUE TITLE
[请问go-admin有支持mongodb的计划吗？]

### ISSUE THREAD

**Issue by orichi** [GoAdminGroup/go-admin#318]
### 需求描述 
俺们项目需要基于mongodb来做，请问go-admin有支持mongodb的计划吗？

### 其他信息 
有或者没有，请问计划或者原因是什么

**Comment by chenhg5** [comment]
@orichi 目前没有，mongodb跟sql数据库差别大。当下你们可以使用[自定义数据源](http://doc.go-admin.cn/zh/admin/table/basic/#_23)解决。
