### ISSUE TITLE
[BUG] 数据表中id列大小写导致程序崩溃

### ISSUE THREAD

**Issue by JackySmith** [GoAdminGroup/go-admin#320]
### bug 描述 [详细地描述 bug，让大家都能理解]
使用版本2.16

通过xorm自动生成数据表，当id表在数据库中表现为 Id 时，即首字母大写时，再通过 adm generate生成go文件，
再登陆后台，
获取相关表数据时，程序崩溃。
而如果id字段首字母小写时，即使其它字段首字母大写时，程序也正常

### 期望结果 [描述你原本期望看到的结果]

虽然可以通过 xorm生成数据表时指定id小写，但是意味着要改其它很多地方，请问能否使go-admin支持Id首字母大写

### 版本信息:

- GoAdmin 版本：
- golang 版本：
- 浏览器环境：
- 开发环境：

**Comment by chenhg5** [comment]
@JackySmith 设置下主键。参考文档：http://doc.go-admin.cn/zh/plugins/admin/#_6

**Comment by JackySmith** [comment]
对adm generate 生成的文件 逐个修改"Id"为"id"可以解决问题，但在未来新生成时总需要这一步，如果可以兼容就好了

**Comment by JackySmith** [comment]
另外，表名为 Condition时 adm generate 生成出错，可能是与一些语句关键字冲突

**Comment by chenhg5** [comment]
@JackySmith 好的，这个我检查下。
