### ISSUE TITLE
[QUESTION] How to delete the sidebar menu

### ISSUE THREAD

**Issue by MarErm27** [GoAdminGroup/go-admin#327]
I deleted table "posts" from the SQLite DB but it still appears in a sidebar, how to delete it?
![image](https://user-images.githubusercontent.com/56219126/92302118-2e47f780-ef72-11ea-8093-3b10764f221c.png)

**Comment by chenhg5** [comment]
You should delete the corresponding menu Posts in the menu manage page which can be accessed by sidebar menu Admin->Menu.
