### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by scripterkaran** [GoAdminGroup/go-admin#329]
### Bug Description [describe the bug in detail]
The example mentioned in quick start seems to be broken (https://book.go-admin.cn/en/quick_start)

### How to reproduce [describe the steps how to reproduce the bug]
Copy the code into a main.go 
run `go run main.go`

### Expect [describe your expect result]
Should run the admin site.

### Reproduction code [here to show your codes or examples]
Error: 
```
./main.go:22:3: cannot use []config.Database literal (type []config.Database) as type config.DatabaseList in field value
```

### Versions

- GoAdmin version: v1.2.16
- golang version: 1.15
- Browser: Chrome
- OS [e.g. mac OS] MacOS 10.13.6

### Others [screenshots or others info here]

<img width="1129" alt="Screen Shot 2020-09-07 at 10 33 16 PM" src="https://user-images.githubusercontent.com/10154253/92408108-28ad0600-f15a-11ea-88ea-fba32ed2f77d.png">

**Comment by chenhg5** [comment]
@scripterkaran You can use the CLI ```adm``` to initialize a GoAdmin project.

Use the command:

```bash
mkdir myproject
cd myproject
adm init
```

**Comment by Byronium** [comment]
Would be great to update the instructions here to do that instead: https://book.go-admin.cn/en/quick_start

**Comment by jomonkj** [comment]
please update in doc. I have lost my 2 hrs
