### ISSUE TITLE
[BUG] Error install go-admin

### ISSUE THREAD

**Issue by coroo** [GoAdminGroup/go-admin#330]
### Bug Description [describe the bug in detail]
Error when install go-admin 

### How to reproduce [describe the steps how to reproduce the bug]
```
go install github.com/GoAdminGroup/go-admin/adm
```

### Expect [describe your expect result]
Installation done

### Reproduction code [here to show your codes or examples]
Please see screenshot for detail error

### Versions

- GoAdmin version: latest version
- golang version: go version go1.14.5 darwin/amd64
- Browser
- OS [e.g. mac OS]: Mac

### Others [screenshots or others info here]
![Screen Shot 2020-09-09 at 15 54 10](https://user-images.githubusercontent.com/13533557/92577325-b8ff5e00-f2b4-11ea-8bac-b13173a66900.png)

**Comment by hitzhangjie** [comment]
+1

**Comment by chenhg5** [comment]
@coroo Do you use the go module way to install? Set the environment variable ```GO111MODULE=on``` and turn on the go module mechanism can solve your problem.
