### ISSUE TITLE
近期开发项

### ISSUE THREAD

**Issue by fym201** [GoAdminGroup/go-admin#35]
近期正在使用go-admin做一个后台，需要补充一些功能，大致开发计划如下

**1.实现对不可编辑字段的处理（除file/iconpicker类型外 已完成）**
   对于标记为不可编辑的字段，前端应显示为不可修改，后端应禁止提交

**2.Table修改为interface，以方便定制开发 （已完成）**
   将Table定义为接口可以方便用户自定义数据处理逻辑，以适应更加复杂的需要（如：多数据源、复杂关联查询、nosql数据源等）

**3.将Row传递给FieldValueFun，以方便根据其它字段定制显示内容(已完成)**
  将整行数据传给字段处理函数，可以方便处理函数根据数据上下文定制显示内容，很多情况下某个字段在客户端展示的结果需要结合其它字段进行判断

**4.列表页字段增加Hide参数(已完成)**
   有些数据字段在客户端并不需要展示，但在处理函数需要用到

**5.筛选项支持使用选择列表**

**6. 筛选项支持直接在列表页显示**

#34

**Comment by chenhg5** [comment]
@fym201 已合并
