### ISSUE TITLE
[Question] Performing soft delete on items

### ISSUE THREAD

**Issue by daivikd3v** [GoAdminGroup/go-admin#354]
### Description [describe your questions]
I want to modify delete button behavior to perform soft delete to set deleted_at to current time.
I cannot find any option to override delete button functionality.

**Comment by Lifelong-Study** [comment]
`
info := userTable.GetInfo().SetFilterFormLayout(form.LayoutThreeCol)
	
info.SetDeleteFn(func(idArr []string) error {
	// do something
	return nil
})
`
