### ISSUE TITLE
[BUG]搜索结果表格中按字段排序行为错误

### ISSUE THREAD

**Issue by centipede510** [GoAdminGroup/go-admin#360]
### bug 描述 [详细地描述 bug，让大家都能理解]
在搜索呈现的内容中点击按某字段排序，结果显示内容丢失搜索条件

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
1. 表格设置为可按某些字段搜索，可按某些字段排序
2. 点击搜索，输入条件显示搜索结果
3. 在搜索结果表格中点击可排序的字段
4. 结果为显示所有行

### 期望结果 [描述你原本期望看到的结果]
期待结果为在搜索内容的基础上进行排序，但排序之后显示结果为所有的行，丢失了搜索条件

### 版本信息:
1.2.17

**Comment by chenhg5** [comment]
@centipede510 新版本中已修复。先关闭了。
