### ISSUE TITLE
[BUG]通过gorm筛选出的数据是int32类型,导致无法显示

### ISSUE THREAD

**Issue by moon-hzq** [GoAdminGroup/go-admin#362]
### bug 描述 [详细地描述 bug，让大家都能理解]
如果mysql的某个字段为 
```
`id` int(11) NOT NULL AUTO_INCREMENT COMMENT '资讯ID',
```
通过 ```info.SetGetDataFn```方法，使用gorm 查询之后的数据 ```var result []map[string]interface{}``` interface是int32类型，跟踪源码，没有匹配int32类型,需要修改
```modules/db/types.go``` 文件中，```GetValueFromJSONOfDatabaseType```这个方法中，第```272```行添加如下代码:
```
} else if v, ok := value.(int32); ok {
			return Value(fmt.Sprintf("%d", v))
		}
```
添加完后,代码片段应该如下:
```
case Contains(typ, IntTypeList):
		if v, ok := value.(float64); ok {
			return Value(fmt.Sprintf("%d", int64(v)))
		} else if v, ok := value.(int64); ok {
			return Value(fmt.Sprintf("%d", v))
		} else if v, ok := value.(int); ok {
			return Value(fmt.Sprintf("%d", v))
		} else if v, ok := value.(int32); ok {
			return Value(fmt.Sprintf("%d", v))
		}
		return "0"
```

### 版本信息:

- GoAdmin 版本：1.2.17
- golang 版本：1.15
- 浏览器环境：
- 开发环境：

**Comment by chenhg5** [comment]
@moon-hzq 提交了一个修复：[#552cb7](https://github.com/GoAdminGroup/go-admin/commit/552cb7ec681e2ad9a90673493e95a0bf60ab11c8)
