### ISSUE TITLE
希望插件开发能增加前后端分离的方式

### ISSUE THREAD

**Issue by SOVLOOKUP** [GoAdminGroup/go-admin#365]
### 需求描述

插件功能的加入极大地增加了项目的灵活性和可拓展性，但是使用模板语法进行前端渲染却与此背道而驰，希望能够兼容前后端分离的方式，能够以插件方式嵌入自己的应用。

### 解决方案

可以启动一个静态服务器，将编译后的前端文件返回

### 其他信息

新建项目的时候希望能自动运行sql脚本

**Comment by chenhg5** [comment]
@SOVLOOKUP 

> 解决方案
> 可以启动一个静态服务器，将编译后的前端文件返回

不太理解你说前后分离的意思。如果是指前端渲染的支持的话，可以参考这个项目：[goadmin-vue-example](https://github.com/GoAdminGroup/goadmin-vue-example)。
如果是指，前端文件可以不通过二进制方式嵌入项目（目前默认是二进制嵌入）的话，目前项目也做了支持。如下：

1. 代码中配置：

```
import _ "github.com/GoAdminGroup/themes/sword/separation"

config.Config{
    Theme: "sword_sep",
    AssetRootPath: "./public/"
}
```

2. 如果启动过了就在数据库中改配置。
然后将资源放在项目文件夹目录的public文件夹下面。
资源：[https://gitee.com/go-admin/themes/tree/master/sword/separation/public](https://gitee.com/go-admin/themes/tree/master/sword/separation/public)
