### ISSUE TITLE
[BUG]自定义表不能新增和编辑

### ISSUE THREAD

**Issue by leeyo** [GoAdminGroup/go-admin#373]
### bug 描述 [详细地描述 bug，让大家都能理解]

todo

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

todo

### 期望结果 [描述你原本期望看到的结果]

todo

### 复现代码 [提供可复现的代码，仓库，或线上示例]

todo

### 版本信息:

- GoAdmin 版本：
- golang 版本：
- 浏览器环境：
- 开发环境：

### 其他信息 [如截图等其他信息可以贴在这里]

<img width="1407" alt="自定义表不能新增和编辑" src="https://user-images.githubusercontent.com/5437347/101627886-fb723b80-3a59-11eb-8b6a-71da45a8649b.png">

**Comment by chenhg5** [comment]
@leeyo 可以提供更多可以复现的信息吗？

**Comment by alonbg** [comment]
Hi guys,
using 1.2.28 with mysql v8.0 (as a google cloud service) and I cant' add new entries to tables from the UI.
Getting the same screen like in the previous  comment.
This is a show stopper for us but I really want to use go-admin. 
Hope this will be fixed soon or can you guide me where to start looking to fix this and I'll send a pull request.

**Comment by chenhg5** [comment]
没有更多信息以供debug，暂时先关闭。
