### ISSUE TITLE
[BUG] modules/db/postgresql.go InitDB缺少连接数和空闲连接数设置

### ISSUE THREAD

**Issue by memetea** [GoAdminGroup/go-admin#379]
### Bug Description [describe the bug in detail]

postgresql的InitDB缺少下面的设置
sqlDB.SetMaxOpenConns(cfg.MaxOpenCon)
sqlDB.SetMaxIdleConns(cfg.MaxIdleCon)

### Versions

- GoAdmin version: [e.g. 1.0.0]
- golang version
- Browser
- OS [e.g. mac OS]

**Comment by chenhg5** [comment]
@memetea 提交了一个修复：[3affd5](https://github.com/GoAdminGroup/go-admin/commit/3affd5674cf079420dd73c4b8bb0211e59e24a9d)
