### ISSUE TITLE
[BUG] adm 生成的项目点击详情按钮无法跳转至详情页面

### ISSUE THREAD

**Issue by gofromzero** [GoAdminGroup/go-admin#391]
### bug 描述 
adm 生成的项目点击详情按钮无法跳转至详情页面
### 复现步骤 
1. 通过adm 工具生成 项目
2. 通过 make generate 生成 数据库表
3. 点击原有数据 和 自定义数据的详情按钮皆无法跳转至详情页面
4. 详情页面的超链接并不是 ```/detail``` ？

### 期望结果
详情按钮能跳转至 详情页面
### 版本信息:

- GoAdmin 版本：v1.2.8
- golang 版本：1.15
- 浏览器环境：Chrome
- 开发环境：windows

**Comment by CloudWarGit** [comment]
同样遇到这个bug

**Comment by lemontreehuang** [comment]
同样遇到这个问题，不知何时修复

**Comment by chenhg5** [comment]
@lemontreehuang @CloudWarGit @gofromzero 已修复。明天会发新版本。[#5950c2](https://github.com/GoAdminGroup/go-admin/commit/5950c25c02bc5387d5182279afc1f02b8a8ad5fb)
