### ISSUE TITLE
[BUG] FileUploadEngine初始化失败

### ISSUE THREAD

**Issue by Halimao** [GoAdminGroup/go-admin#397]
### bug 描述 [详细地描述 bug，让大家都能理解]
使用AddConfigFromJSON初始化配置，设置了FileUploadEngine但是无法生效
### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
config.json
```
"file_upload_engine": {
	"name": "alioss",
	"config": {
		"access_key_id": "*********",
		"access_key_secret": "*********",
		"bucket": "*********",
		"endpoint": "*********",
		"file_dir": "*********"
	}
},
```

main.go
```
...
e := echo.New()
template.AddComp(chartjs.NewChart())
eng := engine.Default()
if err := eng.AddConfigFromJSON("./config.json").AddGenerators(tables.Generators).Use(e); err != nil {
	panic(err)
}

fmt.Println(config.Get().FileUploadEngine.Name)
...
```

### 期望结果 [描述你原本期望看到的结果]

期望输出: alioss
实际输出: ""

### 版本信息:

- GoAdmin 版本：v1.2.18 latest
- golang 版本：go1.15.5 windows/amd64
- 浏览器环境：无
- 开发环境：无

### 其他信息 [如截图等其他信息可以贴在这里]

Use(e)内部调用eng.initSiteSetting(), 进而调用eng.config.Update, 然后在 eng.config.ToMap()位置，ToMap方法实现缺失了FileUploadEngine字段的映射，进而在eng.config.Update方法实现内部，获取"file_upload_engine"字段为空，覆盖了原先从Configuration.json读取到的值。

![image](https://user-images.githubusercontent.com/25278203/104938773-7d0aa100-59ea-11eb-8610-f10431995696.png)
![image](https://user-images.githubusercontent.com/25278203/104938865-a1667d80-59ea-11eb-8d5b-0f1e71e63e8c.png)

**Comment by jooyyy** [comment]
同样的问题，会导致文件上传失败，需要修复

**Comment by chenhg5** [comment]
@Halimao @jooyyy 

配置文件只会在第一次启动时起作用，后续都是从数据库中读取配置。可以尝试在网站右上角进行设置：

![](https://tva1.sinaimg.cn/large/008eGmZEly1gna5rom07ej30dl05dt8t.jpg)
