### ISSUE TITLE
[BUG] a detail-only or an empty info view is not working

### ISSUE THREAD

**Issue by alonbg** [GoAdminGroup/go-admin#399]
### Bug Description
Trying to create a view with an empty `info` list.
Only when a filter is applied, the info list is populated and the user can click for details.

So I tried to avoid `info` from showing with dummy functions at `info.SetQueryFilterFn` or `info.SetGetDataFn`.
This worked but returned no results which I could work with.
- `config.SetOnlyDetail()` also does not have any effect.
- Setting filters to `detail` fields also does not appear to have any effect.
- Applying  `HidePagination()` and `HideRowSelector()`  on `info` has no effect.

If I'm setting `info` without any fields I'm getting:
`controller/handler.go:31        runtime error: invalid memory address or nil pointer dereference`
I also tried setting `config.SetSourceURL("/info/my_table/detail")` which didn't work.

Working just with `detail` and with no `info` results in:
`ERROR   controller/handler.go:31        Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
github.com/GoAdminGroup/go-admin/plugins/admin/controller.(*Handler).GlobalDeferHandler`

To avoid this, I must use `info` and at least the primary key and the field I'm using to filter with.
But it seems I can't change the default `info` query to return no result.

Also, it seems like `FieldJoin` does not work for `detail` fields. A function like `FieldDisplayFromTable` would be very handy. Similar to the functionality of [this example  in table/generators.go](https://github.com/GoAdminGroup/go-admin/blob/60b186b5d982ba245413322ef8faed47c6ae7efb/plugins/admin/modules/table/generators.go#L304)

### How to reproduce
See code example below

### Expect 
A view with an initial empty `info` result. 
I would like to avoid exposing the entire table.
Only when applying a filter a result is returned.
Specifically in this example, only when filtering with the exact `license_hash` a result shall be displayed.
### Reproduction code 

```golang
package tables

import (
	"github.com/GoAdminGroup/go-admin/context"
	"github.com/GoAdminGroup/go-admin/modules/db"
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
	"github.com/GoAdminGroup/go-admin/template/types"
)

func GetBackendLicenseHashTable(ctx *context.Context) table.Table {

	config := table.DefaultConfigWithDriverAndConnection("mysql", "business")
	//config.SetSourceURL("/info/license_hash/detail")
	config.SetCanAdd(false)
	config.SetEditable(false)
	config.SetDeletable(false)
	config.SetExportable(false)
	config.SetOnlyDetail()

	backendLicense := table.NewDefaultTable(config)

	info := backendLicense.GetInfo().HideFilterArea().HidePagination().HideNewButton().
		HideExportButton().HideEditButton().HideRowSelector().HideDeleteButton()

	// info.SetQueryFilterFn(func(param parameter.Parameters, conn db.Connection) (ids []string, stopQuery bool) {
	// 	return []string{}, true
	// })

	// info.SetGetDataFn(func(param parameter.Parameters) ([]map[string]interface{}, int) {
	// 	return []map[string]interface{}{}, 1
	// })

	info.AddField("Id", "id", db.Int).FieldHide()
	info.AddField("License_hash", "license_hash", db.Varchar).
		FieldFilterable().FieldHide()

	info.SetTable("backend_license").SetTitle("BackendLicense").SetDescription("BackendLicense")
	//detail := backendLicense.GetDetailFromInfo()

	detail := backendLicense.GetDetail()

	detail.AddField("License_type", "license_type", db.Varchar)

	detail.AddField("License_length", "license_length", db.Varchar)

	detail.AddField("License_hash", "license_hash", db.Varchar).
		FieldFilterable()

	detail.AddField("Expiry_date", "expiry_date", db.Datetime)

	detail.AddField("Created", "created", db.Datetime)
	detail.AddField("Updated", "updated", db.Datetime)

	detail.AddField("Claimed_user", "username", db.Int).
		FieldJoin(types.Join{
			Table:     "backend_customuser",
			JoinField: "id",
			Field:     "claimed_user_id",
		})

	detail.AddField("Customer", "name", db.Int).
		FieldJoin(types.Join{
			Table:     "backend_customer",
			JoinField: "id",
			Field:     "customer_id",
		})

	
	detail.SetTable("backend_license").SetTitle("BackendLicense").SetDescription("BackendLicense")

	return backendLicense
}
```
### Versions

- GoAdmin version: 1.2.19
- golang version: 1.15.7
- Browser: chrome
- OS: mac OS

**Comment by chenhg5** [comment]
@alonbg You can use the API ``` SetGetDataFn```. However, it needs you to query the data yourself according to the parameter.

```
info.SetGetDataFn(func(params parameter.Parameters) ([]map[string]interface{}, int) {
       xxx := params.GetFieldValue("xxx")
       // query data or not
})
```

**Comment by alonbg** [comment]
@chenhg5 Thank you. I decided to take a different approach.
There are runtime and sql errors described above. So I'll leave the closing decision to you :)
