### ISSUE TITLE
[BUG] SetGetDataFn会导致程序crash

### ISSUE THREAD

**Issue by CloudWarGit** [GoAdminGroup/go-admin#400]
### bug 描述 [详细地描述 bug，让大家都能理解]
给详情页设置自定义的获取数据函数会导致程序崩溃
crash位置如下图：
<img width="821" alt="image" src="https://user-images.githubusercontent.com/10798768/105932178-7a154d80-6087-11eb-9d42-2a07a6413f7d.png">

### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
```
detail := honeycombTasks.GetDetail()
detail.SetGetDataFn(fn)
```
运行程序
### 期望结果 [描述你原本期望看到的结果]
正常从自定义的GetDataFn中获取数据

### 复现代码 [提供可复现的代码，仓库，或线上示例]
```
detail := honeycombTasks.GetDetail()
detail.SetGetDataFn(fn)
```
### 版本信息:

- GoAdmin 版本：1.2.19
- golang 版本：1.15
- 浏览器环境：
- 开发环境：

### 其他信息 [如截图等其他信息可以贴在这里]
plugins/admin/modules/table/default.go的1075-1080行
```
func (tb *DefaultTable) db() db.Connection {
	if tb.connectionDriver != "" && tb.getDataFromDB() {
		return db.GetConnectionFromService(services.Get(tb.connectionDriver))
	}
	return nil
}
```

plugins/admin/modules/table/default.go的1096-1098行
```
func (tb *DefaultTable) getDataFromDB() bool {
	return tb.sourceURL == "" && tb.getDataFun == nil && tb.Info.GetDataFn == nil && tb.Detail.GetDataFn == nil
}
```

tb.Info.GetDataFn不为空时，会使db.Connection为nil，导致空指针

**Comment by chenhg5** [comment]
@CloudWarGit 已修复。[1e48ee3](https://github.com/GoAdminGroup/go-admin/commit/1e48ee35600d4964cbb6ca25e6d641e66bc064d5)
