### ISSUE TITLE
[Proposal] 在不同的电脑上写代码，生成的config.json里面的绝对路径会导致无法运行

### ISSUE THREAD

**Issue by plumk97** [GoAdminGroup/go-admin#402]
### 需求描述 [详细地描述需求，让大家都能理解]
config.json 里面的log路径等都是绝对路径 就导致无法运行 换个电脑就要改一下

**Comment by dk333** [comment]
可以用相对路径的，不过得在网站里改

**Comment by chenhg5** [comment]
@dk333 很好的建议👍会尽快进行支持。
