### ISSUE TITLE
[BUG]make generate 新增table默认disable

### ISSUE THREAD

**Issue by 17liang** [GoAdminGroup/go-admin#408]
### 问题描述 [详细地描述问题，让大家都能理解]

通过make generate命令生成的table默认
FieldDisableWhenCreate().FieldDisableWhenUpdate()导致新建的时候空表单
### 示例代码 [如果有必要，展示代码，线上示例，或仓库]
formList.AddField("Name", "name", db.Varchar, form.Text).
		FieldDisableWhenCreate().
		FieldDisableWhenUpdate()

**Comment by chenhg5** [comment]
@17liang 提交了一个修复。[284ec1](https://github.com/GoAdminGroup/go-admin/commit/284ec1fea52ff84512fe9e84fd813d16d70b29ad)
