### ISSUE TITLE
分页数据不准确，列表内有多行数据，但是下面分页显示只有1条数据 showing 1 to 1 of 1 entries  [BUG]

### ISSUE THREAD

**Issue by junyongNie** [GoAdminGroup/go-admin#412]
### bug 描述 [详细地描述 bug，让大家都能理解]
分页数据不准确，列表内有多行数据，但是下面分页显示只有1条数据
showing 1 to 1 of 1 entries 

### 版本信息:

**### **官网演示站点 http://demo.go-admin.com/admin/info/profile****

- GoAdmin 版本：
- golang 版本：
- 浏览器环境：
- 开发环境：

### 其他信息 [如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/17874475/109386108-7f3e1480-7933-11eb-8103-a6a382b47850.png)

**Comment by chenhg5** [comment]
@junyongNie 提交了修复。[#9fbb80](https://github.com/GoAdminGroup/go-admin/commit/9fbb80f2bb64d1e13f6460cb6377b362f9e2390b)

**Comment by junyongNie** [comment]
> @junyongNie 提交了修复。[#9fbb80](https://github.com/GoAdminGroup/go-admin/commit/9fbb80f2bb64d1e13f6460cb6377b362f9e2390b)

修复很及时，感谢
