### ISSUE TITLE
[BUG] eng.AddConfig传入的config是值传递,tag@v1.2.22

### ISSUE THREAD

**Issue by SealinGp** [GoAdminGroup/go-admin#428]
### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]
按照github README.md教程写了一个main.go,里面的
eng.AddConfig传入的config是值传递,而值传递带有sync.RWMutex,sync.RWMutex是不可复制的
当前tag@v1.2.22没有修复这个问题,望发个版本搞定这个问题

### 期望结果 [描述你原本期望看到的结果]
eng.AddConfig传入的config是改成指针传递

### 版本信息:
- GoAdmin 版本：v1.2.22
- golang 版本：go1.13

**Comment by SealinGp** [comment]
已通过go get xxx@指定commit号解决

**Comment by sgioia9** [comment]
In case anyone's wondering, `ffa1e5525e85add52b3632243ead50923e5794ae` worked for me
