### ISSUE TITLE
升级到1.2.23后，连接数据库提示表都找不到

### ISSUE THREAD

**Issue by Julyyq** [GoAdminGroup/go-admin#469]
从1.2.17升级到1.2.23之后，数据库表都找不到，数据库使用的是pg.

![Screenshot 2021-10-04 at 15 32 33](https://user-images.githubusercontent.com/2620575/135812730-de109035-5aed-42e0-9a87-f8aec3ee6936.png)

**Comment by chenhg5** [comment]
数据库表是否存在，连接地址是否准确。能否最小复现？如果还有问题，麻烦重新打开这个issue。
