### ISSUE TITLE
same error catch twice?

### ISSUE THREAD

**Issue by zychappy** [GoAdminGroup/go-admin#47]
/admin/info/user 
ERRO[1425] Error 1146: Table 'goadmin.users' doesn't exist 
ERRO[1425] goroutine 167 [running]:
...
[GIN] 2019/08/02 - 14:52:09 | 500 |         1m43s |             ::1 | GET      /admin/info/user?_pjax=%23pjax-container
INFO[1427] [GoAdmin]  200   GET    /admin/info/user 
ERRO[1427] Error 1146: Table 'goadmin.users' doesn't exist 
ERRO[1427] goroutine 167 [running]:

**Comment by chenhg5** [comment]
@zychappy import the sql first
