### ISSUE TITLE
error msg is not clear

### ISSUE THREAD

**Issue by zychappy** [GoAdminGroup/go-admin#48]
错误信息提示不明显；
1、新增用户报错，但是数据库 增加了一条新的记录；
add new user error,but new info has been stored in goadmin_users;
2、点击查看 管理-用户 报一下错误；
click admin->users,error:
[GIN] 2019/08/02 - 15:56:03 | 500 |         1m16s |             ::1 | GET      /admin/info/manager?_pjax=%23pjax-container
INFO[5301] [GoAdmin]  200   GET    /admin/info/manager 
ERRO[5301] interface conversion: interface {} is nil, not string

**Comment by chenhg5** [comment]
@zychappy 你使用go-admin版本号和你的配置代码可以提供下吗

**Comment by zychappy** [comment]
latest master

only modify config
demo->main
```
cfg := config.Config{
		DATABASE: []config.Database{
			{
				HOST:         "localhost",
				PORT:         "3306",
				USER:         "test",
				PWD:          "test",
				NAME:         "goadmin", //database name
				MAX_IDLE_CON: 50,
				MAX_OPEN_CON: 150,
				DRIVER:       "mysql",
			},
		},
		DOMAIN: "localhost",
		PREFIX: "admin",
		STORE: config.Store{
			PATH:   "/Users/dev/goadmin",
			PREFIX: "uploads",
		},
		LANGUAGE: "cn",
		INDEX:    "/",
	}
```

**Comment by chenhg5** [comment]
问题太久，而目前CI无法重现。
