### ISSUE TITLE
怎么能把 info 组件里面。进行 where IN 筛选？[Question]

### ISSUE THREAD

**Issue by cs-sea** [GoAdminGroup/go-admin#490]
### 问题描述 [详细地描述问题，让大家都能理解]
怎么能把 info 组件里面。进行 where IN 筛选？
### 示例代码 [如果有必要，展示代码，线上示例，或仓库]
info.WhereRaw("application.id = ?", v)

**Comment by chenhg5** [comment]
@cs-sea 

```
info.WhereRaw("application.id in (?, ?, ?)", []interface{}{1, 2, 3}...)
```

**Comment by cs-sea** [comment]
所以我要提前 知道 这个in 里面有多少个元素，之后写多少个？，这样操作吗？
