### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lnyyj** [GoAdminGroup/go-admin#492]
### bug 描述 [详细地描述 bug，让大家都能理解]
 rbac有问题
### 复现步骤 [清晰描述复现步骤，让别人也能看到问题]

给了一个用户所有权限，这个用户就可以看到所有菜单项

### 期望结果 [描述你原本期望看到的结果]
只可以看到角色组在配置的菜单

### 版本信息:

- GoAdmin 版本：
- golang 版本：
- 浏览器环境：
- 开发环境：

**Comment by chenhg5** [comment]
@lnyyj 目前默认```所有权限```为超管默认拥有所有菜单可见权限。需要隔离菜单建议不要使用```所有权限```，另外再进行配置。http://doc.go-admin.cn/zh/admin/rbac/
