### ISSUE TITLE
Support go fiber

### ISSUE THREAD

**Issue by piyongcai** [GoAdminGroup/go-admin#494]
### Description [describe your advice]
Fiber is a Go web framework built on top of Fasthttp, the fastest HTTP engine for Go. It's designed to ease things up for fast development with zero memory allocation and performance in mind.

### Solution [if any solutions, describe here]

Add go fiber web framework

**Comment by chenhg5** [comment]
Supported.  See: https://github.com/GoAdminGroup/go-admin/blob/master/examples/gofiber/main.go
