### ISSUE TITLE
[BUG] Cannot access website after make serve

### ISSUE THREAD

**Issue by phommata** [GoAdminGroup/go-admin#504]
### Bug Description [describe the bug in detail]

I am unable to log the login screen after going through `adm init` or `adm init web` and `make serve` successfully runs. I already have postgres and the database loaded successfully. There are no logs nor print statements.

[http://127.0.0.1:80/admin/login](http://127.0.0.1/admin/login)

### How to reproduce [describe the steps how to reproduce the bug]

`
1. Download and import the corresponding SQL file:
[Postgresql](https://raw.githubusercontent.com/GoAdminGroup/go-admin/master/data/admin.pgsql)

2. Execute the following command in turn

> make init module=test
> GORPOXY=https://goproxy.io make install
> make serve

go run .
GoAdmin is now running. 
Running in "debug" mode. Switch to "release" mode in production.

2022-04-11T23:21:40.238-0700	INFO	engine/engine.go:402	=====> Initialize database connections
2022-04-11T23:21:40.294-0700	INFO	engine/engine.go:402	=====> Initialize configuration
2022-04-11T23:21:40.298-0700	INFO	engine/engine.go:402	=====> Initialize navigation buttons
2022-04-11T23:21:40.298-0700	INFO	engine/engine.go:402	=====> Initialize plugins
2022-04-11T23:21:40.298-0700	INFO	engine/engine.go:402	=====> Initialize success🍺🍺
`

### Expect [describe your expect result]
Successfully access and log into http://127.0.0.1:80/admin/login.

### Reproduction code [here to show your codes or examples]
`
package main

import (
	"log"
	"os"
	"os/signal"

	_ "github.com/GoAdminGroup/go-admin/adapter/fasthttp"            // web framework adapter
	_ "github.com/GoAdminGroup/go-admin/modules/db/drivers/postgres" // sql driver
	_ "github.com/GoAdminGroup/themes/sword"                         // ui theme

	"github.com/GoAdminGroup/go-admin/engine"
	"github.com/GoAdminGroup/go-admin/template"
	"github.com/GoAdminGroup/go-admin/template/chartjs"
	"github.com/buaazp/fasthttprouter"
	"github.com/valyala/fasthttp"

	"lilac/models"
	"lilac/pages"
	"lilac/tables"
)

func main() {
	startServer()
}

func startServer() {
	router := fasthttprouter.New()

	template.AddComp(chartjs.NewChart())

	eng := engine.Default()

	if err := eng.AddConfigFromJSON("./config.json").
		AddGenerators(tables.Generators).
		Use(router); err != nil {
		panic(err)
	}

	eng.HTML("GET", "/admin", pages.GetDashBoard)
	eng.HTMLFile("GET", "/admin/hello", "./html/hello.tmpl", map[string]interface{}{
		"msg": "Hello world",
	})

	models.Init(eng.PostgresqlConnection())

	router.ServeFiles("/uploads/*filepath", "./uploads")

	go func() {
		_ = fasthttp.ListenAndServe(":80", router.Handler)
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt)
	<-quit
	log.Print("closing database connection")
	eng.PostgresqlConnection().Close()
}
`

### Versions

- GoAdmin version: v1.2.23
- golang version: 1.16.6 darwin/amd64
- Browser: 15.4 (16613.1.17.1.11, 16613)
- OS: macOS 11.6.5 (20G527)

### Others [screenshots or others info here]
postgres shows created tables.
`
test=# \dt
                  List of relations
 Schema |           Name           | Type  |  Owner   
--------+--------------------------+-------+----------
 public | goadmin_menu             | table | postgres
 public | goadmin_operation_log    | table | postgres
 public | goadmin_permissions      | table | postgres
 public | goadmin_role_menu        | table | postgres
 public | goadmin_role_permissions | table | postgres
 public | goadmin_role_users       | table | postgres
 public | goadmin_roles            | table | postgres
 public | goadmin_session          | table | postgres
 public | goadmin_site             | table | postgres
 public | goadmin_user_permissions | table | postgres
 public | goadmin_users            | table | postgres
(11 rows)
`

**Comment by phommata** [comment]
I changed the port to 8080.

**Comment by chenhg5** [comment]
您的邮件我已经收到啦，会及时给您回复~
