### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wivw0306** [GoAdminGroup/go-admin#514]
- OS [e.g. mac OS]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/95760640/171789025-5b8c47a0-1baf-4fa3-898a-657d5744aa5d.png">

**Comment by chenhg5** [comment]
Duplicate of https://github.com/GoAdminGroup/go-admin/issues/114

**Comment by chenhg5** [comment]
Duplicate of https://github.com/GoAdminGroup/go-admin/issues/93
