### ISSUE TITLE
[Question]  刷新按钮可以自定义执行逻辑吗

### ISSUE THREAD

**Issue by oldwang12** [GoAdminGroup/go-admin#522]
我的表格是从mysql获取的数据，我如何点击刷新，然后去执行我自己的业务逻辑去更新mysql

<img width="601" alt="image" src="https://user-images.githubusercontent.com/67354376/184111980-b0f6ca1f-4b61-483b-beab-6f95fd917de5.png">

**Comment by chenhg5** [comment]
@oldwang12 目前不行，没有相关api。刷新就是刷新页面。可以考虑自定义按钮，http://doc.go-admin.cn/zh/admin/table/basic/#_20
