### ISSUE TITLE
[Question] 问个笨蛋问题，菜单怎么改？

### ISSUE THREAD

**Issue by cupen** [GoAdminGroup/go-admin#599]
###  问题描述
如题，是否该有个 go 对象能关联到菜单？

### 示例代码
无

**Comment by chenhg5** [comment]
http://doc.go-admin.cn/zh/admin/menus/

**Comment by cupen** [comment]
> http://doc.go-admin.cn/zh/admin/menus/

收到，谢谢。 我试试用代码控制，毕竟多个环境每个都手动操作很麻烦。
