### ISSUE TITLE
[Proposal] Adding Chi Router Support

### ISSUE THREAD

**Issue by mshafiee** [GoAdminGroup/go-admin#60]
Adding Chi Router Support:
chi is a lightweight, idiomatic and composable router for building Go HTTP services. It's especially good at helping you write large REST API services that are kept maintainable as your project grows and changes. chi is built on the new context package introduced in Go 1.7 to handle signaling, cancelation and request-scoped values across a handler chain.
https://github.com/go-chi/chi

**Comment by chenhg5** [comment]
working on it.
