### ISSUE TITLE
[Question] How To Get Current Selected Form Value for Filter The Selection in Next Form?

### ISSUE THREAD

**Issue by muhAzri** [GoAdminGroup/go-admin#603]
How will the fieldOptionFromTable is display only the sections that have the same course_id as the selected Course Id defined earlier in the formList?

The code is 

```
formList.AddField("Course", "course_id", db.UUID, form.SelectSingle).FieldOptionsFromTable("courses", "name", "id")

formList.AddField("Course Section", "course_section_id", db.UUID, form.SelectSingle).FieldOptionsFromTable("course_section", "name", "id")
```

I know that we can use this code to filter the FieldOptionsFromTable but i dont know how to get current selected value of Course ID
```
formList.AddField("Course Section", "course_section_id", db.UUID, form.SelectSingle).FieldOptionsFromTable("course_section", "name", "id", func(sql *db.SQL) *db.SQL {
    SelectedCourseID :=  I HAVE NOT IDEA HOW TO DO THIS

    return sql.Where("course_id", "=", SelectedCourseID )
})
```

**Comment by chenhg5** [comment]
In this situation, you can use `FieldOnChooseAjax`.
For example：https://github.com/GoAdminGroup/demo.go-admin.cn/blob/master/tables/user.go#L115

**Comment by muhAzri** [comment]
okay i'll try that thanks for the response
