### ISSUE TITLE
i try to change Go-Admin config but nothings change

### ISSUE THREAD

**Issue by sinaw369** [GoAdminGroup/go-admin#608]
Hello, I am facing an issue with the GO-Admin example. I have created a fork from the repository and tried to change the logo, but nothing seems to work. I need to see the changes made to the logo. Could you please guide me on this?
https://github.com/sinaw369/Go-AdminPanel

**Comment by sinaw369** [comment]
i found a way

**Comment by ErfanTech** [comment]
It would be great to share your solution

**Comment by sinaw369** [comment]
> It would be great to share your solution

hi bro,whats your problem with the go-admin config
