### ISSUE TITLE
RESTful json api support?

### ISSUE THREAD

**Issue by SuperGod** [GoAdminGroup/go-admin#63]
Is this project supported RESTful json api?

**Comment by chenhg5** [comment]
@SuperGod not yet

**Comment by hudongcheng** [comment]
请问，有计划增加该功能吗？

**Comment by chenhg5** [comment]
新版本已增加。

**Comment by kirachen1991** [comment]
> 新版本已增加。

怎么支持？好像没有看到设置content-type的地方，components.Form()
