### ISSUE TITLE
按照文档的步骤安装后报错

### ISSUE THREAD

**Issue by a190992** [GoAdminGroup/go-admin#74]
**问题描述** `go run main.go`: # github.com/GoAdminGroup/go-admin/plugins/admin/modules
../github.com/GoAdminGroup/go-admin/plugins/admin/modules/helper.go:42:19: multiple-value uuid.NewV4() in single-value context

**Comment by chenhg5** [comment]
@a190992 依赖问题，不熟悉golang包加载可以直接下载vendor：http://file.go-admin.cn/go_admin/vendor/v1_0_4/vendor.zip

**Comment by a190992** [comment]
谢谢，下载vendor已解决
