### ISSUE TITLE
按照示例，工程不能启动，go新手求助！

### ISSUE THREAD

**Issue by hongbinzhang** [GoAdminGroup/go-admin#75]
**问题描述** 
按照文档介绍启动工程报错，在代码中提示找不到 "github.com/GoAdminGroup/go-admin/modules/db/drivers/mysql"

**示例代码** 
从文档中拷贝的main.go代码

**其他信息**
![2019-10-26_182933](https://user-images.githubusercontent.com/2801250/67618188-942a0580-f81e-11e9-95fa-0b9f94882f91.png)

![2019-10-26_182657](https://user-images.githubusercontent.com/2801250/67618179-765ca080-f81e-11e9-89f0-06b942ead96a.png)

**Comment by chenhg5** [comment]
@hongbinzhang 你好，将 _ "github.com/GoAdminGroup/go-admin/modules/db/drivers/mysql" 这一行先删除试一下，今晚或明天会更新版本修复这个问题

**Comment by wtupyu** [comment]
问题解决了吗，我这里也是按照示例文档中拷贝的main.go代码，运行老是报错，提示见截图
![图片](https://user-images.githubusercontent.com/50827699/68102811-4b093e00-ff0f-11e9-95f9-3075d9d16b28.png)

**Comment by chenhg5** [comment]
@wtupyu ```connection refused``` 检查下你的数据库设置是否正确

**Comment by keeleys** [comment]
https://github.com/keeleys/go-admin-demo
弄了个docker 启动的demo
