### ISSUE TITLE
[adm生成配置问题]为什么我用adm配置生成配置文件过程不报错也不会有配置文件生成

### ISSUE THREAD

**Issue by UncleChJJ** [GoAdminGroup/go-admin#77]
![image](https://user-images.githubusercontent.com/35246151/67834432-5aa91100-fb22-11e9-982d-069270ac55cc.png)

**Comment by chenhg5** [comment]
@UncleChJJ 更新到v1.0.6试一下

**Comment by JasonHonor** [comment]
You need merge #76 then rebuild adm.
