### ISSUE TITLE
[Question] Using admin CLI

### ISSUE THREAD

**Issue by vincegio** [GoAdminGroup/go-admin#78]
I am wondering how to use the admin cli.
Got myself a database locally (tried sqlite and postgres), with a table and some data.
It seems that I am always getting the error of no table in the database.

`go-admin cli error: no tables, you should build a table of your own business first.`

The database clearly consists of a table.
Anything I could do to try to fix this?

**Comment by chenhg5** [comment]
@vincegio what is the version of your admin cli?

**Comment by vincegio** [comment]
@chenhg5 Sorry forgot that one
`GoAdmin CLI v1.0.6`

Installed today.

**Comment by vincegio** [comment]
Managed to get it working by adding a random character to the password imput when selecting postgres.

The user I am connecting with is postgres without a password, not sure how this works when I am applying an invalid password in the end.

Files were generated, and I hooked the Generators to NewAdmin but the endpoint is `runtime error: invalid memory address or nil pointer dereference`

Progress, I guess.

**Comment by chenhg5** [comment]
@vincegio Ok, you can give me the error stack here which can help me to debug.

**Comment by vincegio** [comment]
Hey, 
I added another value to DatabaseList, called it "test" with config to the postgres database.

In the generated function which is named "GetAccountTable" for me, I changed table.DefaultConfigWithDriver to table.DefaultConfigWithDriverAndConnection, specifying postgresql and test as the variables.

Like so:
`accountTable := table.NewDefaultTable(table.DefaultConfigWithDriverAndConnection("postgresql", "test"))`

I am no longer getting the error I mentioned, but am getting: 
`pq: relation "account" does not exist`
I can guarantee that the table is created and I can query it manually. It is under the public schema.


This is the stacktrace if you are interested:

> ERRO[0003] pq: relation "account" does not exist        
ERRO[0003] goroutine 11 [running]:
runtime/debug.Stack(0xc0000e60e0, 0xc000000002, 0xc0002b21c8)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/GoAdminGroup/go-admin/plugins/admin/controller.GlobalDeferHandler(0xc000250180)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/plugins/admin/controller/handler.go:29 +0xb5
panic(0xfcd4e0, 0xc00025b7a0)
        /usr/lib/go/src/runtime/panic.go:679 +0x1b2
github.com/GoAdminGroup/go-admin/modules/db.CommonQuery(0xc0001f40c0, 0xc00029c410, 0x49, 0xc000280f00, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/modules/db/performer.go:18 +0x731
github.com/GoAdminGroup/go-admin/modules/db.(*Postgresql).QueryWithConnection(0x18aa590, 0x10bbe69, 0x4, 0xc00029c2d0, 0x47, 0xc000280f00, 0x2, 0x2, 0x4, 0xc00024d4c0, ...)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/modules/db/postgresql.go:35 +0xd6
github.com/GoAdminGroup/go-admin/plugins/admin/modules/table.DefaultTable.GetDataFromDatabase(0xc0001f4480, 0xc0000b28f0, 0x10c2116, 0xa, 0x10bbe69, 0x4, 0x10101, 0x10bb15c, 0x3, 0x10baeaa, ...)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/plugins/admin/modules/table/table.go:371 +0x1d5f
github.com/GoAdminGroup/go-admin/plugins/admin/controller.showTable(0xc000250180, 0x1233660, 0xc0000792c0, 0xc000266004, 0x13, 0x10baca8, 0x1, 0x10bad6a, 0x2, 0x10baeaa, ...)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/plugins/admin/controller/show.go:51 +0x9c
github.com/GoAdminGroup/go-admin/plugins/admin/controller.ShowInfo(0xc000250180)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/plugins/admin/controller/show.go:44 +0x85c
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000250180)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/context/context.go:59 +0x44
github.com/GoAdminGroup/go-admin/modules/auth.(*Invoker).Middleware.func1(0xc000250180)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/modules/auth/middleware.go:77 +0x2ef
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000250180)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/context/context.go:59 +0x44
github.com/GoAdminGroup/go-admin/plugins/admin.globalErrorHandler(0xc000250180)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/plugins/admin/router.go:62 +0x5b
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000250180)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/context/context.go:59 +0x44
github.com/GoAdminGroup/go-admin/adapter/gin.(*Gin).Use.func1(0xc00027e000)
        {*my_folder*}go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.6/adapter/gin/gin.go:57 +0x30c
github.com/gin-gonic/gin.(*Context).Next(0xc00027e000)
        {*my_folder*}go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc00027e000)
        {*my_folder*}go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 +0x64
github.com/gin-gonic/gin.(*Context).Next(0xc00027e000)
        {*my_folder*}go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc00027e000)
        {*my_folder*}go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/logger.go:240 +0xe1
github.com/gin-gonic/gin.(*Context).Next(0xc00027e000)
        {*my_folder*}go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00017e3c0, 0xc00027e000)
        {*my_folder*}go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b2
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00017e3c0, 0x1220f40, 0xc000278000, 0xc000264000)
        {*my_folder*}go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x134
net/http.serverHandler.ServeHTTP(0xc0001f0620, 0x1220f40, 0xc000278000, 0xc000264000)
        /usr/lib/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00022df40, 0x1222f40, 0xc000250000)
        /usr/lib/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2927 +0x38e

**Comment by chenhg5** [comment]
@vincegio Thanks. Have you set the "test" database connection configuration in the global config?

**Comment by vincegio** [comment]
The config is set up like so:
```go
cfg := config.Config{
	Databases: config.DatabaseList{
		"default": {
			Driver: config.DriverSqlite,
			File:   "./admin.db",
		},
		"test": {
			Host:       "127.0.0.1",
			Port:       "5432",
			User:       "postgres",
			Name:       "godmin",
			MaxIdleCon: 50,
			MaxOpenCon: 150,
			Driver:     config.DriverPostgresql,
		},
	},
	UrlPrefix: "admin",
	Store: config.Store{
		Path:   "./uploads",
		Prefix: "uploads",
	},
	Language:    language.EN,
	IndexUrl:    "/",
	Debug:       true,
	ColorScheme: adminlte.ColorschemeSkinBlack,
}
```

"godmin" is another copy of the go-admin tables and such, but just reused this with the "account" table.

**Comment by chenhg5** [comment]
@vincegio Hey~ I have added a new dev [branch](https://github.com/GoAdminGroup/go-admin/tree/dev.db_postgresql_bug_fix.v1.0.6) and made a commit to fix it. Could you help me to do a test? Thanks.

**Comment by vincegio** [comment]
Cool, Will check it out in a moment. How would I get this tho? Clone it out myself and install it from there I guess?

**Comment by vincegio** [comment]
Seems like I could just go get with the branch, so doing this and double checking that the code is applied and this is the only copy in my go/pkg/mod folder, I am still getting the issue of no relation.

Posting the stack trace just in case.
```
ERRO[0007] pq: relation "account" does not exist
ERRO[0007] goroutine 11 [running]:
runtime/debug.Stack(0xc0000f40e0, 0xc000000002, 0xc0003581c8)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/GoAdminGroup/go-admin/plugins/admin/controller.GlobalDeferHandler(0xc000030280)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/plugins/admin/controller/handler.go:29 +0xb5
panic(0xfcd4e0, 0xc000220480)
        /usr/lib/go/src/runtime/panic.go:679 +0x1b2
github.com/GoAdminGroup/go-admin/modules/db.CommonQuery(0xc0001f60c0, 0xc000026550, 0x49, 0xc00000ee40, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/modules/db/performer.go:18 +0x731
github.com/GoAdminGroup/go-admin/modules/db.(*Postgresql).QueryWithConnection(0x18aa590, 0x10bbe69, 0x4, 0xc000026410, 0x47, 0xc00000ee40, 0x2, 0x2, 0x4, 0xc00022c0f0, ...)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/modules/db/postgresql.go:35 +0xd6
github.com/GoAdminGroup/go-admin/plugins/admin/modules/table.DefaultTable.GetDataFromDatabase(0xc0001f6540, 0xc0000c08f0, 0x10c211c, 0xa, 0x10bbe69, 0x4, 0x10101, 0x10bb15c, 0x3, 0x10baeaa, ...)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/plugins/admin/modules/table/table.go:371 +0x1d5f
github.com/GoAdminGroup/go-admin/plugins/admin/controller.showTable(0xc000030280, 0x1233580, 0xc0000792c0, 0xc000028404, 0x13, 0x10baca8, 0x1, 0x10bad6a, 0x2, 0x10baeaa, ...)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/plugins/admin/controller/show.go:51 +0x9c
github.com/GoAdminGroup/go-admin/plugins/admin/controller.ShowInfo(0xc000030280)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/plugins/admin/controller/show.go:44 +0x85c
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000030280)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/context/context.go:59 +0x44
github.com/GoAdminGroup/go-admin/modules/auth.(*Invoker).Middleware.func1(0xc000030280)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/modules/auth/middleware.go:77 +0x2ef
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000030280)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/context/context.go:59 +0x44
github.com/GoAdminGroup/go-admin/plugins/admin.globalErrorHandler(0xc000030280)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/plugins/admin/router.go:62 +0x5b
github.com/GoAdminGroup/go-admin/context.(*Context).Next(0xc000030280)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/context/context.go:59 +0x44
github.com/GoAdminGroup/go-admin/adapter/gin.(*Gin).Use.func1(0xc0000c0420)
        (...)/go/pkg/mod/github.com/!go!admin!group/go-admin@v1.0.7-0.20191031033240-114e0f45b286/adapter/gin/gin.go:57 +0x30c
github.com/gin-gonic/gin.(*Context).Next(0xc0000c0420)
        (...)/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc0000c0420)
        (...)/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/recovery.go:83 +0x64
github.com/gin-gonic/gin.(*Context).Next(0xc0000c0420)
        (...)/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0000c0420)
        (...)/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/logger.go:240 +0xe1
github.com/gin-gonic/gin.(*Context).Next(0xc0000c0420)
        (...)/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:124 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00018c3c0, 0xc0000c0420)
        (...)/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:389 +0x5b2
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00018c3c0, 0x1220e60, 0xc0001f41c0, 0xc000126200)
        (...)/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/gin.go:351 +0x134
net/http.serverHandler.ServeHTTP(0xc0001f4620, 0x1220e60, 0xc0001f41c0, 0xc000126200)
        /usr/lib/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000241d60, 0x1222e60, 0xc00017bb00)
        /usr/lib/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2927 +0x38e 
```
