### ISSUE TITLE
[BUG] XSS

### ISSUE THREAD

**Issue by No-Github** [GoAdminGroup/go-admin#80]
**bug 描述** 多处存在XSS问题，看样子并没有任何过滤

**复现步骤** 这里就举一个例子，【用户】-->【新建】-->用户名填写【<script>alert(123)</script>】

![image](https://i.imgur.com/oqfYytq.jpg)
![image](https://i.imgur.com/LtP6hsy.jpg)

**期望结果** 做好过滤

**复现代码** <script>alert(123)</script>

**版本信息:**  Version v1.0.6 

- GoAdmin 版本: [e.g. 1.0.0]
- golang 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**其他信息**

**Comment by No-Github** [comment]
![image](https://i.imgur.com/dO8dULP.jpg)
![image](https://i.imgur.com/wd8gz4k.jpg)
这2个地方也有

**Comment by chenhg5** [comment]
@No-Github 框架不会强制进行过滤，用户可以利用提供的过滤api过滤，但是可以考虑增加一个帮助函数，详见文档中admin插件[表格](http://www.go-admin.cn/docs/#/admin/table/basic?id=%e4%bf%ae%e6%94%b9%e6%98%be%e7%a4%ba%e8%be%93%e5%87%ba)和[表单](http://www.go-admin.cn/docs/#/plugins/admin?id=%e8%bf%87%e6%bb%a4%e5%87%bd%e6%95%b0filterfn%e4%b8%8e%e8%a1%a8%e5%8d%95%e8%bf%87%e6%bb%a4%e5%87%bd%e6%95%b0postfilterfn%e8%af%b4%e6%98%8e)部分
