### ISSUE TITLE
[Question]project可以run起来了，但是用adm生成sqlite数据库表报错

### ISSUE THREAD

**Issue by gerrywp** [GoAdminGroup/go-admin#81]
**Description** [describe your questions]
go-admin cli error: near "show": syntax error
**Example code** [If you have any code info]

**Others** [screenshots or other info]
![image](https://user-images.githubusercontent.com/16008976/68079336-0b652800-fe23-11e9-892a-3da4fb235004.png)

**Comment by chenhg5** [comment]
@gerrywp master分支已经修复这个问题，预计今晚发布新版本。 #79

**Comment by gerrywp** [comment]
@chenhg5  v1.0.7可以生成了，但是你们的生成逻辑应该是弄反了。
数据库字段类型如下：

```sql
id             INTERGER   
```
        
然后你们生成的代码

```go
// db.INTERGER也大写了
formList.AddField("Id", "id", db.INTERGER , form.Default).FieldNotAllowAdd()
```
应该判断

```go 
switch databaseFiled.Type.ToUpper(){
case "INTERGER":
formList.AddField("Id", "id", db.Interger, form.Default).FieldNotAllowAdd()
}
```

**Comment by gerrywp** [comment]
请问怎么加入你们，给你们贡献源码？

**Comment by chenhg5** [comment]
@gerrywp 直接提交pr就可以了，这里是[贡献指引](https://github.com/GoAdminGroup/go-admin/blob/master/CONTRIBUTING_CN.md)
