### ISSUE TITLE
[Question] Chartjs 的图表只能硬编码吗？

### ISSUE THREAD

**Issue by skilxn-go** [GoAdminGroup/go-admin#82]
**问题描述** [详细地描述问题，让大家都能理解]
Chartjs 的图表只能硬编码？
有办法在用户访问的时候通过 HTTP/Ajax 或者随便什么方法远程获取实时数据吗？

**示例代码** [如果有必要，展示代码，线上示例，或仓库]

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by skilxn-go** [comment]
fix title

**Comment by chenhg5** [comment]
@skilxn-go 目前可以通过插件的方式实现这个功能，前端js定时拉取插件后端api数据。如果是要做监控系统的话，现在一个兼容和类似grafana的监控插件```monitor```正在开发，预计要一到两周后开发到基础可用版本。

**Comment by skilxn-go** [comment]
能支持 grafana 就太好了。。。考虑对接 prometheus 么？

**Comment by skilxn-go** [comment]
@chenhg5 支持 Grafana 的 feature 目前进展如何？

**Comment by chenhg5** [comment]
@skilxn-go 还在开发中，项目地址：https://github.com/GoAdminGroup/monitor
