### ISSUE TITLE
[Question] Pull request build failed. #83 #84

### ISSUE THREAD

**Issue by JasonHonor** [GoAdminGroup/go-admin#85]
**Description** [describe your questions]

Pull request #83 #84 build failed  , why?

**Example code** [If you have any code info]

**Others** [screenshots or other info]

**Comment by chenhg5** [comment]
@JasonHonor You check it out by running ```make test``` in the GoAdmin project root directory.

**Comment by JasonHonor** [comment]
Ok, thanks.
