### ISSUE TITLE
按照示例文档中的main.go的代码，无法使用？GO新手求助。

### ISSUE THREAD

**Issue by wtupyu** [GoAdminGroup/go-admin#88]
**问题描述** [按照示例文档中的main.go的代码，无法使用？GO新手求助。]

**示例代码** 
package main

import (
	_ "github.com/GoAdminGroup/go-admin/adapter/gin" // 引入适配器，必须引入，如若不引入，则需要自己定义
	_ "github.com/GoAdminGroup/themes/adminlte" // 必须引入，不然报错
	_ "github.com/GoAdminGroup/go-admin/modules/db/drivers/mysql"
	"github.com/GoAdminGroup/go-admin/engine"
	"github.com/GoAdminGroup/go-admin/examples/datamodel"
	"github.com/GoAdminGroup/go-admin/modules/config"
	"github.com/GoAdminGroup/go-admin/modules/language"
	"github.com/GoAdminGroup/go-admin/plugins/admin"
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()

	// 实例化一个GoAdmin引擎对象
	eng := engine.Default()

	// GoAdmin全局配置，也可以写成一个json，通过json引入
	cfg := config.Config{
		Databases: config.DatabaseList{
			"default": {
				Host:       "127.0.0.1",
				Port:       "3306",
				User:       "root",
				Pwd:        "root",
				Name:       "godmin",
				MaxIdleCon: 50,
				MaxOpenCon: 150,
				Driver:     config.DriverMysql,
			},
		},
		UrlPrefix: "admin", // 访问网站的前缀
		// Store 必须设置且保证有写权限，否则增加不了新的管理员用户
		Store: config.Store{
			Path:   "./uploads",
			Prefix: "uploads",
		},
		Language: language.CN,
	}

	// 这里引入你需要管理的业务表配置
	// 关于Generators，详见 https://github.com/GoAdminGroup/go-admin/blob/master/examples/datamodel/tables.go
	adminPlugin := admin.NewAdmin(datamodel.Generators)

	// 增加配置与插件，使用Use方法挂载到Web框架中
	_ = eng.AddConfig(cfg).AddPlugins(adminPlugin).Use(r)

	_ = r.Run(":9033")
}

**其他信息**
 
![2019-11-03 22-27-47屏幕截图](https://user-images.githubusercontent.com/50827699/68102909-b6eba680-ff0f-11e9-882b-a022d06cad7e.png)

**Comment by chenhg5** [comment]
@wtupyu ```connection refused```，看看是不是数据库连接设置错了

**Comment by wtupyu** [comment]
下载的example可以运行了，想提两个问题：
1.登录页面怎么修改标题
2.自定义页面可以调用静态html页面吗？
谢谢

**Comment by wtupyu** [comment]
github.com/GoAdminGroup/go-admin/plugins/admin/modules/constant/constant.go 里面可以改标题

**Comment by chenhg5** [comment]
@wtupyu http://www.go-admin.cn/docs/#/quick_start
