### ISSUE TITLE
[BUG] info box 无法使用 font-awesome 图标

### ISSUE THREAD

**Issue by skilxn-go** [GoAdminGroup/go-admin#89]
**bug 描述** [详细地描述 bug，让大家都能理解]

设置 info-box 的 Icon 为 font-awesome 图标时不生效。

**复现步骤** [清晰描述复现步骤，让别人也能看到问题]
```go
infobox1 := infobox.New().
		SetText("CPU TRAFFIC").
		SetColor("#3583af").
		SetNumber("100").
		SetIcon(`<i class="fa fa-tint" aria-hidden="true"></i>`).
		GetContent()

```

**期望结果** [描述你原本期望看到的结果]
infobox 使用 fa 的图标
实际上最终图标没有，

![image](https://user-images.githubusercontent.com/8231208/68123025-cf2ae800-ff46-11e9-8ef6-a45a783ac465.png)

同时，发现 fa-tint 直接从 class 里面消失了：
![image](https://user-images.githubusercontent.com/8231208/68123071-ec5fb680-ff46-11e9-982b-8a0d1e5ef3f5.png)
只剩下了 fa 这个 class

也尝试了类似 smallbox 的 SetIcon("fa-tint").
同样无法生效

**复现代码** [提供可复现的代码，仓库，或线上示例]

**版本信息:**

- GoAdmin 版本: 1.0.6
- golang 版本: go1.13 darwin/amd64
- 浏览器环境: Chrome 最新稳定版
- 开发环境: Mac OS

**其他信息** [如截图等其他信息可以贴在这里]

**Comment by chenhg5** [comment]
@skilxn-go 试一下```SetIcon("fa-tint")```

**Comment by skilxn-go** [comment]
@chenhg5 问题描述中有阐述，我尝试过 SetIcon("fa-tint") 的方式，最终效果和直接写 <i> 标签完全一致，class 内只剩下了 "fa "，不清楚 fa-tint 是在哪里被过滤掉了吗？

**Comment by chenhg5** [comment]
@skilxn-go 可以提供下主题的版本吗？尝试下更新到最新再试一下。

**Comment by skilxn-go** [comment]
@chenhg5 我切换到最新的版本，goadmin v1.0.7 和 themes v0.0.7，依然存在，你那边能复现吗？

**Comment by skilxn-go** [comment]
@chenhg5 哦不，最新版本通过SetIcon("fa-tint") 的方式可以 work，但是 SetIcon(`<i>....</i>`) 这种方式依然 fail

**Comment by skilxn-go** [comment]
啊啊啊啊啊啊                  啊啊啊啊啊啊啊
