### ISSUE TITLE
[BUG] Add a missing Custom form type in fields

### ISSUE THREAD

**Issue by vborisov** [GoAdminGroup/go-admin#92]
**Bug Description** When it's used form.Custom it generates an error: "undefined: "github.com/GoAdminGroup/go-admin/template/types/form".Custom".

**How to reproduction** I created a plugin and add fields for it. When I tried to use form.Custom for example:
`formPanel.AddField("", "section_homepage", db.Varchar, form.Custom).FieldCustomContent("<h3>Homepage</h3>")`,
the code stopped to run.

**Expect** I expect this field to be valid.

**Versions**

- GoAdmin version: 1.0.6
- golang version: go version go1.13.3 linux/amd64
- Browser: Google Chrome
- OS Ubuntu 16.04.6 LTS

**Others** 
The problem can be easy fix with adding the Custom field in `github.com/GoAdminGroup/go-admin/template/types/form.go`

**Comment by chenhg5** [comment]
Fixed in the newest version.
