### ISSUE TITLE
[BUG] multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by vborisov** [GoAdminGroup/go-admin#93]
**Bug Description** ../github.com/GoAdminGroup/go-admin/plugins/admin/modules/helper.go:42:19: multiple-value uuid.NewV4() in single-value context

**How to reproduction** Just use the latest Go distribution with the latest GoAdmin lib.

**Expect** The project to start.

**Versions**

- GoAdmin version: 1.0.6
- go version go1.13.3 linux/amd64
- OS Ubuntu 16.04.6 LTS

**Others**
An easy fix will be changing the Uuid function to:
`

func Uuid() string {
  u, _ := uuid.NewV4()
  return u.String()
  // return uuid.NewV4().String()
}`

**Comment by chenhg5** [comment]
@vborisov In the latest version of [go.uuid](https://github.com/satori/go.uuid/blob/master/generator.go#L68), the api ```NewV4()``` has only one return value.

**Comment by vborisov** [comment]
It's very strange as I'm with the same version of go.uuid and the latest of Golang it generates an error.

**Comment by kotleta** [comment]
Hello!

I have the same problem.

go1.16.9 linux/amd64
github.com/GoAdminGroup/go-admin v1.2.23
github.com/satori/go.uuid v1.2.0

```
go build -mod vendor my-admin
# github.com/GoAdminGroup/go-admin/plugins/admin/modules
vendor/github.com/GoAdminGroup/go-admin/plugins/admin/modules/helper.go:50:19: multiple-value uuid.NewV4() in single-value context
make: *** [my-admin] Error 2
```

 Could you reopen the issue, please?
