### ISSUE TITLE
[Question]有没有新建按钮来请求外部链接的功能

### ISSUE THREAD

**Issue by wzyonggege** [GoAdminGroup/go-admin#95]
有没有新建按钮来请求外部链接的功能？
调用外部服务

**Comment by hzeyuan** [comment]
你可以尝试在表格中自定义返回a标签,来请求外部链接.类似于这样：
>// 输出html
info.AddField("Name", "name", db.Varchar).FieldDisplay(func(model types.FieldModel) interface{} {    
    return "<span class='label'>" +  model.Value + "</span>"
})
>

**Comment by chenhg5** [comment]
@wzyonggege 当前最新版本，可以增加按钮，使用api：

```
info.AddButton(...)
```

**Comment by wzyonggege** [comment]
> ```
> info.AddButton(...)
> ```

好的 感谢
