### ISSUE TITLE
[Proposal] form select support filter in db

### ISSUE THREAD

**Issue by EchoUtopia** [GoAdminGroup/go-admin#98]
**Description** [describe your advice]

go admin is great and i love it, but when i use it, i got some problems:

- the docs about form is empty: 
https://www.go-admin.com/docs/#/admin/form/components?id=selectbox

- i want to filter select list in db which is now happened in front end. when the select list is very long, it will perform poorly

**Solution** [if any solutions, describe here]

- add support for filter in server rather than front-end for `form.Select`

**Others** [screenshots and other info]

**Comment by hzeyuan** [comment]
hello,i think you can do like this:
> file in /go-admin@v1.0.7/plugins/admin/modules/table/generators.go
>
```
formList.AddField(lg("role"), "role_id", db.Varchar, form.Select).
		FieldOptions(roles).FieldDisplay(func(model types.FieldModel) interface{} {
		roleModel, _ := db.Table("goadmin_role_users").Select("role_id").
			Where("user_id", "=", model.ID).All()
		var roles []string
		for _, v := range roleModel {
			roles = append(roles, strconv.FormatInt(v["role_id"].(int64), 10))
		}
		return roles
	})
```

**Comment by EchoUtopia** [comment]
@hzeyuan thanks for reply, i think the example you posted is for filling the value you selected before in the field, it's not for filtering in db

**Comment by chenhg5** [comment]
@EchoUtopia Sorry for replying late. Thanks for your proposal. I have added to the [develop plan](https://github.com/GoAdminGroup/go-admin/projects/3). The docs will be complete this week. I was busy past two weeks, but I am coming back to GoAdmin soon.

**Comment by EchoUtopia** [comment]
@thanks for your work, i hope i can contribute when i get familiar with go admin

**Comment by chenhg5** [comment]
@EchoUtopia Supported yet in the latest version.
